package tca.rules;

import java.util.*;
import tca.model.*;

/** Process (BPD) rules: gateways, events, lanes, error handling, loops, implementation completeness. */
public final class BpdRules {
    private BpdRules() {}
    static final String CAT = "Process";
    public static List<Rule> rules() {
        List<Rule> l = new ArrayList<>();
        l.add(new Rule("TCA-BPD-001", "Gateway without a default path", CAT, Severity.CRITICAL, "An exclusive/inclusive gateway has only conditional outgoing flows. If no condition is true the token is lost and the instance hangs at the gateway.",
                "Mark one outgoing flow as the default (no condition) or make the conditions exhaustive.", "IDA check-bpd-gateway-condition") {
            public void check(RuleContext c, List<Finding> out) {
                for (TwxObject o : c.objects("bpd")) { BpdModel b = c.bpd(o); for (BpdModel.FlowObject f : b.flowObjects) { if (!f.kind().equals("gateway") || "2".equals(f.gatewayType) ) continue; int outs = 0; boolean def = false; for (BpdModel.Flow fl : b.flows) if (fl.fromId.equals(f.id)) { outs++; if (fl.isDefault || fl.condition.trim().isEmpty()) def = true; } if (outs > 1 && !def) out.add(Finding.of(this, o, f.id, f.name, "gateway '" + f.name + "'", "Gateway '" + f.name + "' has " + outs + " conditional flows and no default flow", "")); } }
            }
        }.impact(2));
        l.add(new Rule("TCA-BPD-002", "Activity without implementation", CAT, Severity.MAJOR, "An activity has no attached service / process / script (phantom step). The instance stops at the activity or completes it without doing anything.", "Attach an implementation to the activity or delete it.", "IDA check-bpd-phantom-steps") {
            public void check(RuleContext c, List<Finding> out) { for (TwxObject o : c.objects("bpd")) for (BpdModel.FlowObject f : c.bpd(o).flowObjects) if (f.kind().equals("activity") && f.attachedRef.isEmpty() && f.script.trim().isEmpty() && !f.xml.contains("<attachedExternalActivityId>") && !f.xml.contains("linkedBpd") && !f.xml.contains("<attachedBpdRef>") && !f.xml.contains("<attachedCase")) out.add(Finding.of(this, o, f.id, f.name, "activity '" + f.name + "'", "Activity '" + f.name + "' has no implementation", "")); }
        });
        l.add(new Rule("TCA-BPD-003", "Implementation not in the export", CAT, Severity.CRITICAL, "An activity references a service or process that does not exist in the application or its bundled toolkits.", "Re-attach the activity to an existing implementation and verify the toolkit versions.", "") {
            public void check(RuleContext c, List<Finding> out) { for (TwxObject o : c.objects("bpd")) for (BpdModel.FlowObject f : c.bpd(o).flowObjects) if (!f.attachedRef.isEmpty() && c.twx.find(f.attachedRef) == null) out.add(Finding.of(this, o, f.id, f.name, "activity '" + f.name + "'", "Activity '" + f.name + "' references missing artifact " + f.attachedRef, "")); }
        });
        l.add(new Rule("TCA-BPD-004", "Flow object not connected", CAT, Severity.MAJOR, "An activity, gateway or event has no incoming or no outgoing sequence flow.", "Connect the element or remove it; every path must reach an end event.", "IDA check-bpd-step-incorrectly-referenced") {
            public void check(RuleContext c, List<Finding> out) {
                for (TwxObject o : c.objects("bpd")) { BpdModel b = c.bpd(o); Set<String> in = new HashSet<>(), from = new HashSet<>(); for (BpdModel.Flow fl : b.flows) { in.add(fl.toId); from.add(fl.fromId); }
                    for (BpdModel.FlowObject f : b.flowObjects) { if (f.kind().equals("note") || !f.attachedToId.isEmpty()) continue; boolean start = f.kind().equals("event") && ("1".equals(f.eventType) || f.name.toLowerCase().startsWith("start")), end = f.kind().equals("event") && ("2".equals(f.eventType) || f.name.toLowerCase().startsWith("end") || f.xml.contains("<eventType>2"));
                        if (!start && !in.contains(f.id)) out.add(Finding.of(this, o, f.id, f.name, f.kind() + " '" + f.name + "'", capital(f.kind()) + " '" + f.name + "' has no incoming flow", "")); else if (!end && !from.contains(f.id) && !f.attachedToId.isEmpty() == false) { if (!end && !from.contains(f.id)) out.add(Finding.of(this, o, f.id, f.name, f.kind() + " '" + f.name + "'", capital(f.kind()) + " '" + f.name + "' has no outgoing flow", "")); } }
                }
            }
        });
        l.add(new Rule("TCA-BPD-005", "Loop without exit", CAT, Severity.MAJOR, "Sequence flows form a cycle that has no flow leaving it: the process can loop forever (every iteration creates tasks and tracking data).", "Add an exit condition on a gateway inside the loop or a maximum iteration counter.", "IDA check-bpd-contains-infinite-loop") {
            public void check(RuleContext c, List<Finding> out) {
                for (TwxObject o : c.objects("bpd")) { BpdModel b = c.bpd(o); Map<String, List<String>> g = new HashMap<>(); for (BpdModel.FlowObject f : b.flowObjects) g.put(f.id, new ArrayList<String>()); for (BpdModel.Flow fl : b.flows) if (g.containsKey(fl.fromId) && !fl.toId.isEmpty()) g.get(fl.fromId).add(fl.toId);
                    for (List<String> cyc : DependencyRules.cycles(g)) { Set<String> set = new HashSet<>(cyc); boolean exit = false; for (String n : cyc) for (String t : g.get(n)) if (!set.contains(t)) exit = true; StringBuilder sb = new StringBuilder(); for (String n : cyc) { BpdModel.FlowObject f = b.flowObject(n); if (sb.length() > 0) sb.append(" -> "); sb.append(f == null ? n : f.name); }
                        BpdModel.FlowObject first = b.flowObject(cyc.get(0)); if (!exit) out.add(Finding.of(this, o, cyc.get(0), first == null ? "" : first.name, "loop", "Loop without exit: " + sb, "")); }
                }
            }
        });
        l.add(new Rule("TCA-BPD-006", "Human task in a system lane", CAT, Severity.MAJOR, "A user task (human service) is placed in a system lane; it is assigned to the system participant and never appears in anyone's inbox.", "Move the activity to a lane with the right team, or change the implementation to a system service.", "IDA check-bpd-humanservice-in-system-lane") {
            public void check(RuleContext c, List<Finding> out) { for (TwxObject o : c.objects("bpd")) for (BpdModel.FlowObject f : c.bpd(o).flowObjects) if (f.systemLane && f.kind().equals("activity") && isHuman(c, f)) out.add(Finding.of(this, o, f.id, f.name, "activity '" + f.name + "'", "Human task '" + f.name + "' is in the system lane '" + f.laneName + "'", "")); }
        });
        l.add(new Rule("TCA-BPD-007", "Lane or team assigned to All Users", CAT, Severity.MAJOR, "A lane (or its team) is bound to the default 'All Users' participant. Tasks become visible to everybody, which is a security and usability problem.", "Assign a dedicated team (participant group) to the lane and manage its members.", "IDA check-lane-participant-not-default") {
            public void check(RuleContext c, List<Finding> out) { for (TwxObject o : c.objects("bpd")) for (BpdModel.Lane ln : c.bpd(o).lanes) { if (ln.system) continue; TwxObject t = c.twx.find(ln.participantRef); String nm = t == null ? ln.participantRef : t.name; if (ln.participantRef.isEmpty() || nm.equalsIgnoreCase("All Users") || (t != null && t.xml.contains("<isAllUsers>true"))) out.add(Finding.of(this, o, ln.id, ln.name, "lane '" + ln.name + "'", "Lane '" + ln.name + "' is assigned to " + (ln.participantRef.isEmpty() ? "no team" : "'" + nm + "'"), "")); } }
        });
        l.add(new Rule("TCA-BPD-008", "Multi-instance loop on a system activity", CAT, Severity.MAJOR, "A multi-instance loop (MIL) runs on an activity in a system lane. Each iteration runs as a separate task / transaction which is slow for large lists; the same result is usually achieved by a loop inside the service.", "Implement the iteration inside a service flow, or make sure the list is small and the behaviour is intended.", "IDA check-MIL-system-activity") {
            public void check(RuleContext c, List<Finding> out) { for (TwxObject o : c.objects("bpd")) for (BpdModel.FlowObject f : c.bpd(o).flowObjects) if (f.multiInstance && f.systemLane) out.add(Finding.of(this, o, f.id, f.name, "activity '" + f.name + "'", "Multi-instance loop on system activity '" + f.name + "'", "")); }
        });
        l.add(new Rule("TCA-BPD-009", "Message event without an undercover agent", CAT, Severity.MAJOR, "A message (intermediate/start) event has no undercover agent attached; the event can never fire.", "Attach the undercover agent that delivers the message, or remove the event.", "IDA check-bpd-message-event") {
            public void check(RuleContext c, List<Finding> out) { for (TwxObject o : c.objects("bpd")) for (BpdModel.FlowObject f : c.bpd(o).flowObjects) if (f.kind().equals("event") && f.isMessageEvent() && f.ucaRef.isEmpty() && !f.xml.contains("<ucaId>")) out.add(Finding.of(this, o, f.id, f.name, "event '" + f.name + "'", "Message event '" + f.name + "' has no undercover agent", "")); }
        });
        l.add(new Rule("TCA-BPD-010", "Script on a start or end event", CAT, Severity.MAJOR, "Code on start/end events is hidden from the diagram reader and runs outside any activity (no error handling, no tracking).", "Move the code into a system activity (script / service) next to the event.", "IDA check-bpd-event-start-contains-script") {
            public void check(RuleContext c, List<Finding> out) { for (TwxObject o : c.objects("bpd")) for (BpdModel.FlowObject f : c.bpd(o).flowObjects) if (f.kind().equals("event") && f.attachedToId.isEmpty() && !f.script.trim().isEmpty()) out.add(Finding.of(this, o, f.id, f.name, "event '" + f.name + "'", "Event '" + f.name + "' contains a script", "")); }
        });
        l.add(new Rule("TCA-BPD-011", "Activity without error handling", CAT, Severity.MAJOR, "A system activity that calls a service has no error boundary event and the process has no global error handling; a failure leaves the instance in the failed state without a business reaction.", "Attach an error intermediate event to the activity (or a process-level error event) and route it to a handling path (retry, notify, compensate).", "IDA check-bpd-component-need-exception-handle") {
            public void check(RuleContext c, List<Finding> out) { for (TwxObject o : c.objects("bpd")) { BpdModel b = c.bpd(o); boolean global = false; for (BpdModel.FlowObject f : b.flowObjects) if (f.kind().equals("event") && f.attachedToId.isEmpty() && f.isErrorEvent()) global = true; if (global) continue; for (BpdModel.FlowObject f : b.flowObjects) if (f.kind().equals("activity") && f.systemLane && !f.attachedRef.isEmpty() && !f.hasErrorHandling) out.add(Finding.of(this, o, f.id, f.name, "activity '" + f.name + "'", "System activity '" + f.name + "' has no error handling", "")); } }
        });
        l.add(new Rule("TCA-BPD-012", "Too many searchable variables", CAT, Severity.CRITICAL, "More than 25 process variables are marked searchable / available in Process Portal. Every searchable field is indexed on each save, which slows instance updates and portal searches.", "Keep only the fields users really search on (typically < 10); consider a custom search using a business data table.", "IDA check-bpd-searchable-field") {
            public void check(RuleContext c, List<Finding> out) { int max = c.threshold("searchableFields", 25); for (TwxObject o : c.objects("bpd")) { int n = c.bpd(o).searchableFields; if (n > max) out.add(Finding.of(this, o, "", "", "variables", n + " searchable fields (max " + max + ")", "")); } }
        }.impact(2));
        l.add(new Rule("TCA-BPD-013", "Long chain of sequential activities in one lane", CAT, Severity.MAJOR, "Many activities follow each other in the same lane without gateways ('string of pearls'). Each activity is a separate task with its own persistence and navigation; the same work in one service is faster and simpler for the user.", "Merge sequential system activities into one service flow; merge sequential human tasks of the same performer into one human service with several coaches.", "IDA check-sequential-activities-in-lane") {
            public void check(RuleContext c, List<Finding> out) { int max = c.threshold("sequentialActivities", 5); for (TwxObject o : c.objects("bpd")) { BpdModel b = c.bpd(o); Map<String, String> next = new HashMap<>(); Map<String, Integer> outs = new HashMap<>(), ins = new HashMap<>(); for (BpdModel.Flow fl : b.flows) { outs.merge(fl.fromId, 1, Integer::sum); ins.merge(fl.toId, 1, Integer::sum); next.put(fl.fromId, fl.toId); }
                    Set<String> done = new HashSet<>(); for (BpdModel.FlowObject f : b.flowObjects) { if (!f.kind().equals("activity") || done.contains(f.id)) continue; List<String> chain = new ArrayList<>(); BpdModel.FlowObject cur = f; while (cur != null && cur.kind().equals("activity") && cur.laneId.equals(f.laneId) && outs.getOrDefault(cur.id, 0) == 1 && (chain.isEmpty() || ins.getOrDefault(cur.id, 0) == 1) && !chain.contains(cur.id)) { chain.add(cur.id); done.add(cur.id); cur = b.flowObject(next.get(cur.id)); }
                        if (chain.size() >= max) { StringBuilder sb = new StringBuilder(); for (String id : chain) { if (sb.length() > 0) sb.append(" -> "); sb.append(b.flowObject(id).name); } out.add(Finding.of(this, o, chain.get(0), f.name, "lane '" + f.laneName + "'", chain.size() + " sequential activities in lane '" + f.laneName + "': " + sb, "")); } } } }
        });
        l.add(new Rule("TCA-BPD-014", "System task not cleaned up after completion", CAT, Severity.CRITICAL, "System lane activities keep their completed tasks; over time the task tables grow and slow down the whole system.", "Enable 'Delete task on completion' (clean up) on system activities that do not need a task history.", "IDA check-delete-completed-task") {
            public void check(RuleContext c, List<Finding> out) { for (TwxObject o : c.objects("bpd")) for (BpdModel.FlowObject f : c.bpd(o).flowObjects) if (f.kind().equals("activity") && f.systemLane && !f.attachedRef.isEmpty() && !f.deleteTaskOnCompletion && !f.xml.contains("<doCloseTask>true") && f.xml.contains("<doCloseTask>")) out.add(Finding.of(this, o, f.id, f.name, "activity '" + f.name + "'", "System activity '" + f.name + "' keeps completed tasks", "")); }
        });
        l.add(new Rule("TCA-BPD-015", "Activity without narrative or subject", "Documentation", Severity.MINOR, "A user activity has no task subject and/or narrative; Process Portal shows an empty or technical title to the user.", "Set the task subject (what to do) and the narrative (instructions) on the activity.", "IDA check-bpd-activity-subject") {
            public void check(RuleContext c, List<Finding> out) { for (TwxObject o : c.objects("bpd")) for (BpdModel.FlowObject f : c.bpd(o).flowObjects) if (f.kind().equals("activity") && !f.systemLane && isHuman(c, f) && (f.subject.trim().isEmpty() || f.narrative.trim().isEmpty())) out.add(Finding.of(this, o, f.id, f.name, "activity '" + f.name + "'", "User task '" + f.name + "' has no " + (f.subject.trim().isEmpty() ? "subject" : "narrative"), "")); }
        });
        l.add(new Rule("TCA-BPD-016", "Process without documentation", "Documentation", Severity.MINOR, "The process has no documentation.", "Describe the business purpose, triggers and outcomes in the process documentation.", "IDA check-bpd-documentation") {
            public void check(RuleContext c, List<Finding> out) { for (TwxObject o : c.objects("bpd")) if (c.bpd(o).documentation.trim().isEmpty()) out.add(Finding.of(this, o, "", "", "", "No documentation", "")); }
        });
        l.add(new Rule("TCA-BPD-017", "Process variable name not lowerCamelCase", "Naming", Severity.MAJOR, "A process variable name is not lowerCamelCase.", "Rename to lowerCamelCase and update mappings.", "IDA check-bpd-variables-naming-conversion") {
            public void check(RuleContext c, List<Finding> out) { for (TwxObject o : c.objects("bpd")) { BpdModel b = c.bpd(o); List<ServiceModel.Variable> all = new ArrayList<>(b.variables); all.addAll(b.parameters); for (ServiceModel.Variable v : all) if (!v.name.isEmpty() && !v.name.matches("[a-z][A-Za-z0-9]*")) out.add(Finding.of(this, o, "", "", "variable '" + v.name + "'", "Variable '" + v.name + "' is not lowerCamelCase", "")); } }
        });
        l.add(new Rule("TCA-BPD-018", "Unused process variable", CAT, Severity.MAJOR, "A process variable is never used in a mapping, condition or script of the process.", "Remove the variable.", "IDA check-bpd-unused-variables") {
            public void check(RuleContext c, List<Finding> out) { for (TwxObject o : c.objects("bpd")) { BpdModel b = c.bpd(o); for (ServiceModel.Variable v : b.variables) if (!v.name.isEmpty() && ServiceRules.count(o.xml, "tw.local." + v.name) == 0) out.add(Finding.of(this, o, "", "", "variable '" + v.name + "'", "Process variable '" + v.name + "' is never used", "")); } }
        });
        l.add(new Rule("TCA-BPD-019", "Timer event without duration or on the critical path", CAT, Severity.INFO, "Timer boundary events are listed for review: check that the durations are configured through EPVs (not hard-coded) and that the repeat behaviour is intended.", "Prefer exposed process values for timer durations so they can be tuned per environment.", "") {
            public void check(RuleContext c, List<Finding> out) { for (TwxObject o : c.objects("bpd")) for (BpdModel.FlowObject f : c.bpd(o).flowObjects) if (f.isTimerEvent() && !f.xml.contains("tw.epv.")) out.add(Finding.of(this, o, f.id, f.name, "event '" + f.name + "'", "Timer event '" + f.name + "' uses a hard-coded duration", "")); }
        });
        l.add(new Rule("TCA-BPD-020", "Auto-tracking enabled on the process", "Performance", Severity.MAJOR, "Auto-tracking writes a tracking event for every activity of every instance to the Performance Data Warehouse. Enabled by default, it is usually not what reporting needs and it costs database I/O on every step.", "Disable auto-tracking on the process and add explicit tracking points / tracking groups for the KPIs that reports need.", "IDA check-auto-tracking-enable") {
            public void check(RuleContext c, List<Finding> out) { for (TwxObject o : c.objects("bpd")) if (c.bpd(o).trackingEnabled) out.add(Finding.of(this, o, "", "", "", "Auto-tracking is enabled", "")); }
        });
        return l;
    }
    static boolean isHuman(RuleContext c, BpdModel.FlowObject f) { TwxObject t = c.twx.find(f.attachedRef); if (t != null && t.type.equals("process")) { return c.service(t).isHuman(); } return "3".equals(f.taskType) || f.xml.contains("<bpmnTaskType>3"); }
    static String capital(String s) { return s.isEmpty() ? s : Character.toUpperCase(s.charAt(0)) + s.substring(1); }
}
