package tca.rules;

import java.util.*;
import java.util.regex.*;
import tca.model.*;
import tca.util.Xml;

/** Static equivalents of the legacy code-analyzer rules that were not covered by the other rule sets (see docs/LEGACY-RULES.md). */
public final class LegacyRules {
    private LegacyRules() {}
    static int count(String s, String sub) { int n = 0, i = 0; while ((i = s.indexOf(sub, i)) >= 0) { n++; i += sub.length(); } return n; }
    static boolean inLoop(String code, Pattern what) {   // pattern occurs inside a for/while/do block (brace depth after a loop keyword)
        String c = ScriptRules.strip(code); Matcher lm = Pattern.compile("\\b(for|while|do)\\b\\s*(\\([^)]*\\))?\\s*\\{").matcher(c);
        while (lm.find()) { int depth = 0, i = lm.end() - 1; int start = i; for (; i < c.length(); i++) { char ch = c.charAt(i); if (ch == '{') depth++; else if (ch == '}') { depth--; if (depth == 0) break; } } if (what.matcher(c.substring(start, Math.min(i + 1, c.length()))).find()) return true; }
        return false;
    }
    public static List<Rule> rules() {
        List<Rule> l = new ArrayList<>();
        l.add(new Rule("TCA-SVC-030", "Integration / service call inside a loop", "Performance", Severity.MAJOR, "A step that calls a web service, Java connector, SQL service or decision service sits inside a loop of the service flow (a cycle of links). Every iteration pays the full call cost (connection, transaction, marshalling); with large lists this is the most common cause of slow services.",
                "Batch the work: call the service once with the whole list, or move the loop into the called service (single transaction), cache lookups outside the loop.", "legacy rules 12, 81, 82, 83") {
            public void check(RuleContext c, List<Finding> out) {
                for (TwxObject o : c.objects("process")) { ServiceModel s = c.service(o); if (s.links.isEmpty()) continue; Map<String, List<String>> g = new HashMap<>(); for (ServiceModel.Item it : s.items) g.put(it.id, new ArrayList<String>()); for (ServiceModel.Link k : s.links) if (g.containsKey(k.fromItemId)) g.get(k.fromItemId).add(k.toItemId);
                    Set<String> inCycle = new HashSet<>(); for (List<String> cyc : DependencyRules.cycles(g)) inCycle.addAll(cyc);
                    for (ServiceModel.Item it : s.items) { if (!inCycle.contains(it.id)) continue; String k = it.kind(); TwxObject t = it.attachedRef.isEmpty() ? null : c.twx.find(it.attachedRef); String tt = t != null && t.type.equals("process") ? c.service(t).processTypeCode : "";
                        boolean heavy = k.equals("integration") || (k.equals("call") && (tt.equals("4") || tt.equals("1") || tt.equals("7") || (t != null && t.name.toLowerCase().matches(".*(sql|execute statement|web service|invoke|call|http|rest|soap|java).*"))));
                        if (heavy) out.add(Finding.of(this, o, it.id, it.name, "step '" + it.name + "'", "Step '" + it.name + "' (" + (t != null ? t.name : it.component) + ") is called inside a loop", "")); }
                }
            }
        });
        l.add(new Rule("TCA-SVC-031", "Many steps before the first coach", "UI", Severity.MAJOR, "A human service runs more than 5 steps (scripts, service calls) before its first coach is shown. The user waits for all of them before seeing anything.", "Show the coach first (with the data available) and load details afterwards with Service Call / Ajax controls; move pre-processing to the process.", "legacy rule 7") {
            public void check(RuleContext c, List<Finding> out) { int max = c.threshold("stepsBeforeCoach", 5); for (TwxObject o : c.objects("process")) { ServiceModel s = c.service(o); if (!s.isHuman()) continue; int n = 0; Set<String> seen = new HashSet<>(); String cur = s.startItemId; while (cur != null && !cur.isEmpty() && seen.add(cur)) { ServiceModel.Item it = s.item(cur); if (it == null || it.kind().equals("coach") || it.kind().equals("exit")) break; if (!it.kind().equals("note")) n++; String next = null; for (ServiceModel.Link k : s.links) if (k.fromItemId.equals(cur)) { next = k.toItemId; break; } cur = next; } if (n > max) out.add(Finding.of(this, o, "", "", "", n + " steps run before the first coach (max " + max + ")", "")); } }
        });
        l.add(new Rule("TCA-SVC-032", "Service with only start and end", "Quality", Severity.MINOR, "The service contains no step besides the start/end points: it is an empty placeholder.", "Implement or delete the service.", "legacy rules 174, 176") {
            public void check(RuleContext c, List<Finding> out) { for (TwxObject o : c.objects("process")) { ServiceModel s = c.service(o); if (s.processTypeCode.equals("5") || s.processTypeCode.equals("13") || s.processTypeCode.equals("9") || s.processTypeCode.equals("11")) continue; int real = 0; for (ServiceModel.Item it : s.items) if (!it.kind().equals("exit") && !it.kind().equals("note") && !it.kind().equals("start")) real++; if (!s.items.isEmpty() && real == 0) out.add(Finding.of(this, o, "", "", "", "Service '" + o.name + "' has no implementation steps", "")); } }
        });
        l.add(new Rule("TCA-SVC-033", "Too many private variables", "Quality", Severity.MINOR, "The service or process declares more than 30 private variables; the execution context becomes large (serialised on every step) and the logic is hard to follow.", "Group related data into business objects, remove unused variables, keep temporary values local to scripts.", "legacy rules 92, 93, 94") {
            public void check(RuleContext c, List<Finding> out) { int max = c.threshold("privateVariables", 30); for (TwxObject o : c.objects("process")) { int n = c.service(o).variables.size(); if (n > max) out.add(Finding.of(this, o, "", "", "variables", n + " private variables (max " + max + ")", "")); } for (TwxObject o : c.objects("bpd")) { int n = c.bpd(o).variables.size(); if (n > max) out.add(Finding.of(this, o, "", "", "variables", n + " private variables (max " + max + ")", "")); } }
        });
        l.add(new Rule("TCA-SVC-034", "Large execution context (business data size)", "Performance", Severity.MAJOR, "The variables of the process / human service reach more than 150 attributes when their business objects are expanded (lists count as their element type). The whole context is serialised on every activity, coach and save; large contexts slow everything down and hit database limits.",
                "Keep only what the process needs (claim-check pattern: store documents / large lists outside and pass references), split the business objects, nullify large lists when done.", "legacy rules 30, 33, 34, 89") {
            public void check(RuleContext c, List<Finding> out) { int max = c.threshold("contextAttributes", 150); for (TwxObject o : c.objects("bpd")) { int n = 0; for (ServiceModel.Variable v : c.bpd(o).variables) n += size(c, v.classRef, 0, new HashSet<String>()); for (ServiceModel.Variable v : c.bpd(o).parameters) n += size(c, v.classRef, 0, new HashSet<String>()); if (n > max) out.add(Finding.of(this, o, "", "", "variables", "Process context has about " + n + " attributes (max " + max + ")", "")); }
                for (TwxObject o : c.objects("process")) { ServiceModel s = c.service(o); if (!s.isHuman()) continue; int n = 0; for (ServiceModel.Variable v : s.variables) n += size(c, v.classRef, 0, new HashSet<String>()); for (ServiceModel.Variable v : s.parameters) n += size(c, v.classRef, 0, new HashSet<String>()); if (n > max) out.add(Finding.of(this, o, "", "", "variables", "Human service context has about " + n + " attributes (max " + max + ")", "")); } }
            int size(RuleContext c, String classRef, int depth, Set<String> seen) { TwxObject t = c.twx.find(classRef); if (t == null || !t.type.equals("twClass") || depth > 6 || !seen.add(t.id)) return 1; int n = 0; for (BusinessObjectModel.Property p : c.bo(t).properties) n += size(c, p.classRef, depth + 1, seen); seen.remove(t.id); return Math.max(1, n); }
        });
        l.add(new Rule("TCA-SVC-035", "Input parameter with a default value", "Quality", Severity.INFO, "An input parameter has a default value. Callers that forget the mapping silently run with the default, which hides integration mistakes.", "Remove defaults from inputs (fail fast) or document why the default is intended.", "legacy rule 60") {
            public void check(RuleContext c, List<Finding> out) { for (TwxObject o : c.objects("process")) { int n = 0; String ev = ""; for (ServiceModel.Variable v : c.service(o).parameters) if (v.input && v.hasDefault && !v.defaultValue.trim().isEmpty()) { n++; if (ev.length() < 100) ev += v.name + " "; } if (n > 0) out.add(Finding.of(this, o, "", "", "parameters", n + " input parameter(s) with default values", ev.trim())); } }
        });
        l.add(new Rule("TCA-SVC-036", "Links with default names", "Quality", Severity.INFO, "Links out of switches / decisions are still named 'Untitled'; the diagram does not tell which condition leads where.", "Name the outgoing links of decisions after their condition (Yes / No / Error ...).", "legacy rule 153") {
            public void check(RuleContext c, List<Finding> out) { for (TwxObject o : c.objects("process")) { ServiceModel s = c.service(o); int n = 0; for (ServiceModel.Link k : s.links) { ServiceModel.Item from = s.item(k.fromItemId); if (from != null && from.kind().equals("decision") && k.name.toLowerCase().startsWith("untitled")) n++; } if (n > 0) out.add(Finding.of(this, o, "", "", "links", n + " decision link(s) named 'Untitled'", "")); } }
        });
        l.add(new Rule("TCA-SVC-037", "Pre/post assignments on start or exit points", "Quality", Severity.MINOR, "Data assignments attached to the start or the exit of a service are invisible in the diagram and run outside the error handling.", "Move the assignments into a script step next to the start / exit.", "legacy rule 161") {
            public void check(RuleContext c, List<Finding> out) { for (TwxObject o : c.objects("process")) for (ServiceModel.Item it : c.service(o).items) if ((it.kind().equals("exit") || it.id.equals(c.service(o).startItemId)) && (!it.preAssignments.isEmpty() || !it.postAssignments.isEmpty())) out.add(Finding.of(this, o, it.id, it.name, "step '" + it.name + "'", "Pre/post assignments on '" + it.name + "'", "")); }
        });
        l.add(new Rule("TCA-SVC-038", "Many pre/post assignments on one step", "Quality", Severity.MINOR, "A step carries more than 10 pre/post assignments; logic hidden in assignments is hard to read and to debug.", "Replace the assignments with an explicit script step or proper data mappings.", "legacy rules 152, 167") {
            public void check(RuleContext c, List<Finding> out) { int max = c.threshold("assignmentsPerStep", 10); for (TwxObject o : c.objects("process")) for (ServiceModel.Item it : c.service(o).items) { int n = it.preAssignments.size() + it.postAssignments.size(); if (n > max) out.add(Finding.of(this, o, it.id, it.name, "step '" + it.name + "'", n + " pre/post assignments on '" + it.name + "'", "")); } }
        });
        l.add(new Rule("TCA-SVC-039", "Service or process exposed to All Users", "Security", Severity.MAJOR, "The artifact is exposed (startable / URL / dashboard) to the default 'All Users' participant.", "Expose it to a dedicated team.", "legacy rules 35, 166") {
            public void check(RuleContext c, List<Finding> out) { for (TwxObject o : c.objects(null)) { if (!o.type.equals("process") && !o.type.equals("bpd")) continue; String ref = Xml.text(o.xml, "participantRef"); if (ref.isEmpty()) continue; TwxObject t = c.twx.find(ref); if (t != null && (t.name.equalsIgnoreCase("All Users") || t.xml.contains("<isAllUsers>true"))) out.add(Finding.of(this, o, "", "", "", o.typeLabel() + " '" + o.name + "' is exposed to All Users", "")); } }
        });
        l.add(new Rule("TCA-SVC-040", "'Unknown' or placeholder text in step names and documentation", "Quality", Severity.MINOR, "Step names or documentation contain 'unknown', 'TODO', 'FIXME' or 'deprecated'.", "Finish or remove the marked artifacts; delete deprecated ones.", "legacy rules 144, 154") {
            public void check(RuleContext c, List<Finding> out) { Pattern p = Pattern.compile("(?i)\\b(unknown|todo|fixme|deprecated|do not use)\\b"); for (TwxObject o : c.objects("process")) { ServiceModel s = c.service(o); for (ServiceModel.Item it : s.items) if (p.matcher(it.name + " " + it.documentation).find()) out.add(Finding.of(this, o, it.id, it.name, "step '" + it.name + "'", "Placeholder text in step '" + it.name + "'", "")); if (p.matcher(s.documentation).find()) out.add(Finding.of(this, o, "", "", "documentation", "Placeholder / deprecated marker in the documentation", "")); } }
        });
        l.add(new Rule("TCA-SVC-041", "Complexity score (steps + decisions + loops)", "Quality", Severity.INFO, "Cyclomatic-style complexity of the flow (links - steps + 2 x decision paths) above 30: the artifact is hard to test completely.", "Split the flow into sub-services / sub-processes with single responsibilities.", "legacy rules 21, 22, 156") {
            public void check(RuleContext c, List<Finding> out) { int max = c.threshold("complexity", 30); for (TwxObject o : c.objects("process")) { ServiceModel s = c.service(o); int cx = s.links.size() - s.items.size() + 2; for (ServiceModel.Item it : s.items) if (it.kind().equals("decision")) cx += 1; if (cx > max) out.add(Finding.of(this, o, "", "", "", "Complexity " + cx + " (" + s.items.size() + " steps, " + s.links.size() + " links)", "")); } for (TwxObject o : c.objects("bpd")) { BpdModel b = c.bpd(o); int cx = b.flows.size() - b.flowObjects.size() + 2; for (BpdModel.FlowObject f : b.flowObjects) if (f.kind().equals("gateway")) cx += 1; if (cx > max) out.add(Finding.of(this, o, "", "", "", "Complexity " + cx + " (" + b.flowObjects.size() + " flow objects, " + b.flows.size() + " flows)", "")); } }
        });
        l.add(new Rule("TCA-BPD-030", "Process with too many activities", "Process", Severity.MINOR, "The process has more than 30 flow objects. Large diagrams are hard to read; sub-processes and linked processes keep the main flow understandable.", "Group phases into sub-processes / linked processes.", "legacy rule 163") {
            public void check(RuleContext c, List<Finding> out) { int max = c.threshold("bpdFlowObjects", 30); for (TwxObject o : c.objects("bpd")) { int n = 0; for (BpdModel.FlowObject f : c.bpd(o).flowObjects) if (f.attachedToId.isEmpty()) n++; if (n > max) out.add(Finding.of(this, o, "", "", "", n + " flow objects (max " + max + ")", "")); } }
        });
        l.add(new Rule("TCA-BPD-031", "Process without notes / documentation on the diagram", "Documentation", Severity.INFO, "The diagram has no note elements; complex processes benefit from notes explaining the business rules on the diagram.", "Add notes for gateways and non-obvious paths.", "legacy rule 157") {
            public void check(RuleContext c, List<Finding> out) { for (TwxObject o : c.objects("bpd")) { BpdModel b = c.bpd(o); if (b.flowObjects.size() > 12 && !o.xml.contains("componentType=\"Note\"") && !o.xml.contains("<note")) out.add(Finding.of(this, o, "", "", "", "No notes on a diagram with " + b.flowObjects.size() + " flow objects", "")); } }
        });
        l.add(new Rule("TCA-JS-030", "Nested loops", "Performance", Severity.MINOR, "A loop inside a loop (quadratic behaviour) on server-side lists; with TW list wrappers each access is slow.", "Index the inner list into a map first (object keyed by id), then look up in the outer loop.", "legacy rule 8") {
            public void check(RuleContext c, List<Finding> out) { Pattern loop = Pattern.compile("\\b(for|while)\\b\\s*\\("); for (Script s : c.allScripts()) { if (s.kind.equals("template")) continue; if (inLoop(s.code, loop)) out.add(Finding.of(this, s.object, s.itemId, ScriptRules.itemName(s), s.location, "Nested loop in " + s.location, "")); } }
        });
        l.add(new Rule("TCA-JS-031", "Deep copy / serialisation inside a loop", "Performance", Severity.MAJOR, "JSON.stringify/parse, clone(), toXML or tw.system.serializer is used inside a loop; each iteration copies whole objects.", "Copy once outside the loop or copy only the fields needed.", "legacy rule 65") {
            public void check(RuleContext c, List<Finding> out) { Pattern p = Pattern.compile("JSON\\.stringify|JSON\\.parse|\\.clone\\s*\\(|toXML|serializer|\\.toString\\s*\\(\\)"); for (Script s : c.allScripts()) { if (s.kind.equals("template")) continue; if (inLoop(s.code, p)) out.add(Finding.of(this, s.object, s.itemId, ScriptRules.itemName(s), s.location, "Copy / serialisation inside a loop in " + s.location, "")); } }
        });
        l.add(new Rule("TCA-JS-032", "Hard-coded JNDI data source, queue or WSDL endpoint", "Configuration", Severity.MAJOR, "A JNDI name (jdbc/..., jms/...) or a WSDL/endpoint URL is hard-coded in a script or mapping; it must change per environment.", "Use an environment variable / EPV for data source names and endpoints (or the server definitions in the process app settings).", "legacy rules 27, 39") {
            public void check(RuleContext c, List<Finding> out) { Pattern p = Pattern.compile("[\"'](jdbc/|jms/|java:comp/env/)[^\"']+[\"']|[\"']https?://[^\"']*\\?wsdl[\"']", Pattern.CASE_INSENSITIVE); for (Script s : c.allScripts()) { Matcher m = p.matcher(s.code); if (m.find()) out.add(Finding.of(this, s.object, s.itemId, ScriptRules.itemName(s), s.location, "Hard-coded resource name " + m.group() + " in " + s.location, "")); } }
        });
        l.add(new Rule("TCA-JS-033", "tw.system.serializer / XML API usage", "Performance", Severity.MINOR, "tw.system.serializer, E4X XML objects or toXMLString are slow and deprecated in BAW.", "Use JSON (JSON.stringify / JSON.parse) and typed business objects.", "legacy rules 69, 74") {
            public void check(RuleContext c, List<Finding> out) { Pattern p = Pattern.compile("tw\\.system\\.serializer|new\\s+XML\\s*\\(|\\.toXMLString\\s*\\(|XMLDocument|tw\\.system\\.xml"); for (Script s : c.allScripts()) { if (s.kind.equals("template")) continue; Matcher m = p.matcher(ScriptRules.strip(s.code)); if (m.find()) out.add(Finding.of(this, s.object, s.itemId, ScriptRules.itemName(s), s.location, m.group() + " used in " + s.location, "")); } }
        });
        l.add(new Rule("TCA-JS-034", "Excessive logging", "Performance", Severity.MINOR, "A script contains more than 5 log statements (log.info / log.debug); in production this floods SystemOut and costs I/O.", "Keep one log statement per business event, use log.debug guarded by a level EPV.", "legacy rule 24") {
            public void check(RuleContext c, List<Finding> out) { int max = c.threshold("logStatements", 5); Pattern p = Pattern.compile("\\blog\\.(info|debug|warn|error)\\s*\\("); for (Script s : c.allScripts()) { Matcher m = p.matcher(ScriptRules.strip(s.code)); int n = 0; while (m.find()) n++; if (n > max) out.add(Finding.of(this, s.object, s.itemId, ScriptRules.itemName(s), s.location, n + " log statements in " + s.location, "")); } }
        });
        l.add(new Rule("TCA-JS-035", "Duplicated function definitions across scripts", "Quality", Severity.MINOR, "The same function name is defined in several scripts / coach views of the application: copied code that has to be maintained in every place.", "Move shared functions to a toolkit web asset (client) or a general system service (server).", "legacy rule 9") {
            public void check(RuleContext c, List<Finding> out) { Map<String, Set<String>> defs = new HashMap<>(); Pattern p = Pattern.compile("\\bfunction\\s+([A-Za-z_$][A-Za-z0-9_$]{3,})\\s*\\("); for (Script s : c.allScripts()) { Matcher m = p.matcher(ScriptRules.strip(s.code)); while (m.find()) { Set<String> set = defs.get(m.group(1)); if (set == null) { set = new TreeSet<>(); defs.put(m.group(1), set); } set.add(s.object.name); } }
                for (Map.Entry<String, Set<String>> e : defs.entrySet()) if (e.getValue().size() > 2 && !e.getKey().matches("(?i)init|load|render|update|main|callback|handler|format|validate|toggle|refresh|setup|show|hide")) out.add(Finding.of(this, null, "", "", "scripts", "Function '" + e.getKey() + "' is defined in " + e.getValue().size() + " artifacts: " + e.getValue(), "")); }
        });
        l.add(new Rule("TCA-UI-010", "Polling with setInterval in a coach view", "Performance", Severity.MINOR, "The coach view polls the server with setInterval / setTimeout loops; every open coach generates constant load.", "Use boundary events / Service Call controls triggered by user actions, or long intervals with a stop condition.", "legacy rules 37, 72") {
            public void check(RuleContext c, List<Finding> out) { for (TwxObject o : c.objects("coachView")) for (CoachViewModel.Script s : c.coachView(o).scripts) if (!s.kind.equals("css") && s.code.contains("setInterval(")) { out.add(Finding.of(this, o, "", "", s.name, "setInterval polling in " + s.name, "")); break; } }
        });
        l.add(new Rule("TCA-UI-011", "Static DOM ids in a coach view", "UI", Severity.MINOR, "The coach view's HTML or scripts use fixed element ids (id=\"...\" without $$viewDOMID$$). Two instances of the view on one page (tables, repeating sections) collide.", "Use class selectors scoped to this.context.element, or prefix ids with $$viewDOMID$$.", "legacy rule 122") {
            public void check(RuleContext c, List<Finding> out) { Pattern p = Pattern.compile("\\bid=\\\\?[\"']([A-Za-z][A-Za-z0-9_-]*)\\\\?[\"']"); for (TwxObject o : c.objects("coachView")) { CoachViewModel v = c.coachView(o); String html = Xml.unescape(v.layoutXml); Set<String> ids = new TreeSet<>(); Matcher m = p.matcher(html); while (m.find()) if (!html.contains("$$viewDOMID$$")) ids.add(m.group(1)); for (CoachViewModel.Script s : v.scripts) if (s.kind.equals("html")) { m = p.matcher(s.code); while (m.find()) if (!s.code.contains("$$viewDOMID$$")) ids.add(m.group(1)); } if (!ids.isEmpty()) out.add(Finding.of(this, o, "", "", "layout", ids.size() + " static DOM id(s): " + ids, "")); } }
        });
        l.add(new Rule("TCA-UI-012", "Change handler without property check", "UI", Severity.MINOR, "The change handler reacts to every change event (binding, options, visibility) without checking event.property; it re-renders too often and may loop when it sets values itself.", "Start the handler with a check on event.property (and event.type) and return otherwise.", "legacy rules 114, 115") {
            public void check(RuleContext c, List<Finding> out) { for (TwxObject o : c.objects("coachView")) for (CoachViewModel.Script s : c.coachView(o).scripts) if (s.kind.equals("handler") && s.name.equals("change") && s.code.trim().length() > 40 && !s.code.contains("property")) out.add(Finding.of(this, o, "", "", "change handler", "change handler does not check event.property", "")); }
        });
        l.add(new Rule("TCA-UI-013", "Lifecycle methods called directly", "UI", Severity.MINOR, "The coach view calls this.load(), this.view() or this.change() itself; the framework calls them, manual calls run initialisation twice and break the event order.", "Move the shared code into a private function called from the lifecycle methods.", "legacy rules 120, 121") {
            public void check(RuleContext c, List<Finding> out) { Pattern p = Pattern.compile("this\\.(load|view|change|unload)\\s*\\(\\s*\\)"); for (TwxObject o : c.objects("coachView")) for (CoachViewModel.Script s : c.coachView(o).scripts) { if (s.kind.equals("css") || s.kind.equals("html")) continue; Matcher m = p.matcher(ScriptRules.strip(s.code)); if (m.find()) { out.add(Finding.of(this, o, "", "", s.name, m.group() + " called in " + s.name, "")); break; } } }
        });
        l.add(new Rule("TCA-UI-014", "Coach view without prototype-level functions", "Performance", Severity.INFO, "The inline JavaScript is executed per instance ('prototype-level functions' unchecked). With many instances (tables, repeating sections) every instance re-creates all functions.", "Enable prototype-level functions when the view has no per-instance closure state, or keep the inline script small.", "legacy rule 119") {
            public void check(RuleContext c, List<Finding> out) { for (TwxObject o : c.objects("coachView")) { CoachViewModel v = c.coachView(o); int lines = 0; for (CoachViewModel.Script s : v.scripts) if (s.kind.equals("inline")) lines += CoachRules.lines(s.code); if (!v.prototypeFunc && lines > 150) out.add(Finding.of(this, o, "", "", "", lines + " inline script lines executed per instance (prototype-level functions off)", "")); } }
        });
        l.add(new Rule("TCA-UI-015", "AMD module dependency declared but not used", "Quality", Severity.MINOR, "The coach view declares AMD dependencies whose function argument never appears in its scripts; they are loaded for nothing.", "Remove unused AMD dependencies.", "legacy rules 77, 97") {
            public void check(RuleContext c, List<Finding> out) { for (TwxObject o : c.objects("coachView")) { CoachViewModel v = c.coachView(o); for (String b : Xml.blocks(o.xml, "amdDependency")) { String arg = Xml.text(b, "functionArgument"); if (arg.isEmpty()) continue; boolean used = false; for (CoachViewModel.Script s : v.scripts) if (!s.kind.equals("css") && Pattern.compile("\\b" + Pattern.quote(arg) + "\\b").matcher(s.code).find()) used = true; if (!used) out.add(Finding.of(this, o, "", "", "AMD dependencies", "AMD dependency '" + Xml.text(b, "moduleId") + "' (" + arg + ") is never used", "")); } } }
        });
        l.add(new Rule("TCA-UI-016", "Many JavaScript / CSS resources on one coach view", "Performance", Severity.MINOR, "The coach view includes more than 4 script or style files; each is a separate request on every coach load.", "Combine the files (one minified bundle per library) and share them through one toolkit.", "legacy rules 123, 124") {
            public void check(RuleContext c, List<Finding> out) { int max = c.threshold("viewResources", 4); for (TwxObject o : c.objects("coachView")) { int n = c.coachView(o).resources.size(); if (n > max) out.add(Finding.of(this, o, "", "", "resources", n + " included files (max " + max + ")", "")); } }
        });
        l.add(new Rule("TCA-UI-017", "Mixed dojo, jQuery and plain DOM APIs in one coach view", "Quality", Severity.INFO, "The coach view mixes dojo (require/dojo.*), jQuery ($) and direct DOM calls; three ways to do the same thing make the code hard to maintain and load extra libraries.", "Pick one approach per toolkit (the BPM UI Toolkit controls use plain DOM + dojo).", "legacy rule 137") {
            public void check(RuleContext c, List<Finding> out) { for (TwxObject o : c.objects("coachView")) { String all = ""; for (CoachViewModel.Script s : c.coachView(o).scripts) if (!s.kind.equals("css")) all += s.code + "\n"; boolean dojo = all.contains("dojo.") || all.contains("require([\"dojo") || all.contains("require(['dojo"), jq = Pattern.compile("(^|[^A-Za-z0-9_])(\\$|jQuery)\\s*\\(").matcher(all).find(), dom = all.contains("document.querySelector") || all.contains("document.getElementById") || all.contains("createElement("); if ((dojo ? 1 : 0) + (jq ? 1 : 0) + (dom ? 1 : 0) >= 3) out.add(Finding.of(this, o, "", "", "scripts", "dojo, jQuery and plain DOM APIs mixed", "")); } }
        });
        l.add(new Rule("TCA-UI-018", "Binding used without null check in a coach view", "Quality", Severity.INFO, "Scripts chain property access directly after context.binding.get(\"value\") (e.g. .get(\"value\").name); when the view is unbound or the value is null the script throws.", "Read the value into a variable and check it before using its properties.", "legacy rule 95, 111") {
            public void check(RuleContext c, List<Finding> out) { Pattern p = Pattern.compile("context\\.binding\\.get\\(\\s*[\"']value[\"']\\s*\\)\\.[A-Za-z_$]"); for (TwxObject o : c.objects("coachView")) { int n = 0; for (CoachViewModel.Script s : c.coachView(o).scripts) { if (s.kind.equals("css") || s.kind.equals("html")) continue; Matcher m = p.matcher(ScriptRules.strip(s.code)); while (m.find()) n++; } if (n > 0) out.add(Finding.of(this, o, "", "", "scripts", n + " direct property access(es) on the binding value without null check", "")); } }
        });
        l.add(new Rule("TCA-APP-040", "Toolkit dependency not used", "Dependencies", Severity.MINOR, "The application depends on a toolkit but references none of its artifacts.", "Remove the dependency (Process Designer: toolkit > remove).", "legacy rule 68") {
            public void check(RuleContext c, List<Finding> out) { Set<String> refs = new HashSet<>(); for (TwxObject o : c.twx.app.objects.values()) refs.addAll(o.refs()); for (TwxPackage.Dependency d : c.twx.app.dependencies) { TwxPackage t = c.twx.toolkits.get(d.snapshotId); if (t == null || d.system || c.isSystem(t)) continue; boolean used = false; for (String id : t.objects.keySet()) if (refs.contains(id)) { used = true; break; } if (!used) out.add(Finding.of(this, null, "", "", "dependencies", "Toolkit '" + d.name + " " + d.snapshotName + "' is not used by the application", "")); } }
        });
        l.add(new Rule("TCA-APP-041", "Environment variable defined in several packages", "Configuration", Severity.MINOR, "The same environment variable name is defined in the application and in a toolkit (or in two toolkits); which value wins depends on the resolution order and confuses administrators.", "Define each environment variable once, in the package that owns it.", "legacy rule 71") {
            public void check(RuleContext c, List<Finding> out) { Map<String, Set<String>> where = new TreeMap<>(); for (TwxPackage p : c.twx.allPackages()) { if (c.isSystem(p)) continue; for (TwxObject o : p.byType("environmentVariableSet")) for (String b : Xml.blocks(o.xml, "environmentVariable")) { String n = Xml.attrOf(b.substring(0, b.indexOf('>')), "name"); if (n.isEmpty()) n = Xml.text(b, "name"); if (n.isEmpty()) continue; Set<String> s = where.get(n); if (s == null) { s = new TreeSet<>(); where.put(n, s); } s.add(p.acronym); } } for (Map.Entry<String, Set<String>> e : where.entrySet()) if (e.getValue().size() > 1) out.add(Finding.of(this, null, "", "", "environment variables", "Environment variable '" + e.getKey() + "' is defined in " + e.getValue(), "")); }
        });
        l.add(new Rule("TCA-APP-042", "Environment variable never used", "Quality", Severity.INFO, "An environment variable is defined but no script references tw.env.<name>.", "Remove unused environment variables.", "legacy rule 113") {
            public void check(RuleContext c, List<Finding> out) { StringBuilder sb = new StringBuilder(); for (TwxObject o : c.twx.app.objects.values()) if (o.type.equals("process") || o.type.equals("bpd") || o.type.equals("coachView")) sb.append(o.xml); String all = sb.toString(); for (TwxObject o : c.twx.app.byType("environmentVariableSet")) for (String b : Xml.blocks(o.xml, "environmentVariable")) { String n = Xml.attrOf(b.substring(0, b.indexOf('>')), "name"); if (n.isEmpty()) n = Xml.text(b, "name"); if (!n.isEmpty() && !all.contains("tw.env." + n)) out.add(Finding.of(this, o, "", n, "environment variable " + n, "Environment variable '" + n + "' is never used", "")); } }
        });
        l.add(new Rule("TCA-APP-043", "Large or unminified web asset", "Performance", Severity.MINOR, "A JavaScript/CSS web asset is larger than 300 KB or is not minified (many line breaks); every coach that includes it downloads it.", "Minify and gzip libraries, split rarely used code, keep assets under 300 KB.", "legacy rules 4, 5, 10") {
            public void check(RuleContext c, List<Finding> out) { long max = c.threshold("assetKb", 300) * 1024L; for (TwxPackage p : c.packages()) for (TwxObject o : p.byType("managedAsset")) { long len = 0; try { len = Long.parseLong(Xml.text(o.xml, "length")); } catch (NumberFormatException e) {} String n = o.name.toLowerCase(); if (len > max && (n.endsWith(".js") || n.endsWith(".css"))) out.add(Finding.of(this, o, "", "", "", "Web asset '" + o.name + "' is " + (len / 1024) + " KB" + (n.contains(".min.") ? "" : " and not minified"), "")); } }
        });
        l.add(new Rule("TCA-APP-044", "Same web asset bundled in several packages", "Quality", Severity.MINOR, "A web asset with the same name exists in the application and in one of its toolkits (or in two toolkits); coaches may load two different versions.", "Keep one copy in a shared UI toolkit.", "legacy rule 40") {
            public void check(RuleContext c, List<Finding> out) { Map<String, Set<String>> where = new TreeMap<>(); for (TwxPackage p : c.twx.allPackages()) { if (c.isSystem(p)) continue; for (TwxObject o : p.byType("managedAsset")) { Set<String> s = where.get(o.name); if (s == null) { s = new TreeSet<>(); where.put(o.name, s); } s.add(p.acronym); } } for (Map.Entry<String, Set<String>> e : where.entrySet()) if (e.getValue().size() > 1) out.add(Finding.of(this, null, "", "", "web assets", "Web asset '" + e.getKey() + "' exists in " + e.getValue(), "")); }
        });
        l.add(new Rule("TCA-QA-010", "EPV / resource bundle linked to a service but not used", "Quality", Severity.MINOR, "The service links an exposed process value or resource bundle that none of its scripts references.", "Remove the unused link.", "legacy rules 106, 108") {
            public void check(RuleContext c, List<Finding> out) { for (TwxObject o : c.objects("process")) { ServiceModel s = c.service(o); if (!s.epvRefs.isEmpty() && !o.xml.contains("tw.epv.")) out.add(Finding.of(this, o, "", "", "EPV links", s.epvRefs.size() + " EPV(s) linked but tw.epv is never used", "")); if (!s.resourceBundleRefs.isEmpty() && !o.xml.contains("tw.resource.")) out.add(Finding.of(this, o, "", "", "resource bundle links", s.resourceBundleRefs.size() + " resource bundle(s) linked but tw.resource is never used", "")); } }
        });
        l.add(new Rule("TCA-QA-011", "Process variable of type ANY", "Data", Severity.MINOR, "A variable is typed ANY: no validation, generic serialisation and no support in client-side coaches for nested lists.", "Use a concrete business object.", "legacy rule 99") {
            public void check(RuleContext c, List<Finding> out) { for (TwxObject o : c.objects(null)) { if (!o.type.equals("process") && !o.type.equals("bpd")) continue; List<ServiceModel.Variable> vs = new ArrayList<>(); if (o.type.equals("process")) { vs.addAll(c.service(o).variables); vs.addAll(c.service(o).parameters); } else { vs.addAll(c.bpd(o).variables); vs.addAll(c.bpd(o).parameters); } int n = 0; String ev = ""; for (ServiceModel.Variable v : vs) if (v.classRef.endsWith("12.c09c9b6e-aabd-4897-bef2-ed61db106297")) { n++; if (ev.length() < 100) ev += v.name + " "; } if (n > 0) out.add(Finding.of(this, o, "", "", "variables", n + " variable(s) typed ANY", ev.trim())); } }
        });
        return l;
    }
}
