package tca;

import java.io.File;
import java.util.*;
import tca.model.*;
import tca.parse.*;

/** Command line: inventory <twx> | analyze <twx> [out.json] [--settings file] [--toolkits] | serve [port] [dataDir] [--host addr] [--workspaces] [--retention-days N] [--read-only-settings] | rules [out.md] | settings [out.json] | baw <op> [argsJson] [folder]. */
public class Main {
    public static void main(String[] a) throws Exception {
        if (a.length == 0) { System.out.println("usage: inventory <twx> | analyze <twx> [out.json] [--settings file.json] [--toolkits] | serve [port] [dataDir] [--host addr] [--no-browser] [--workspaces] [--retention-days N] [--read-only-settings] | rules [out.md] | settings [out.json] | baw <op> [argsJson] [folder]"); return; }
        if (a[0].equals("settings")) {   // full settings document (every rule with its defaults) as the starting point of a customised settings file
            String json = tca.util.Json.writePretty(new tca.rules.RuleSettings().document(new tca.engine.Analyzer().rules()));
            if (a.length > 1) java.nio.file.Files.write(new File(a[1]).toPath(), json.getBytes("UTF-8")); else System.out.println(json); return;
        }
        if (a[0].equals("baw")) { System.out.println(new tca.baw.Facade().call(a[1], a.length > 2 ? a[2] : "{}", a.length > 3 ? a[3] : "")); return; }   // same call as the process application's Java integration
        if (a[0].equals("rules")) {   // markdown catalogue of the rules
            StringBuilder sb = new StringBuilder("# TWX Code Analyzer - rule catalogue\n\nGenerated by `java -jar twx-code-analyzer.jar rules`. Severity weights: Critical 100, Major 40, Minor 10, Info 2 (x impact 1..3) drive the ranking. Severity, impact, weights and thresholds can be customised per rule in the settings (see README, Rule settings).\n");
            String cat = "";
            for (tca.rules.Rule r : new tca.engine.Analyzer().rules()) { if (!r.category.equals(cat)) { cat = r.category; sb.append("\n## ").append(cat).append("\n\n| Id | Severity | Rule | What it checks | Remediation | Reference |\n|---|---|---|---|---|---|\n"); }
                sb.append("| ").append(r.id).append(" | ").append(r.severity.label).append(" | ").append(r.title).append(" | ").append(r.description.replace("|", "/")).append(" | ").append(r.remediation.replace("|", "/")).append(" | ").append(r.reference).append(" |\n"); }
            if (a.length > 1) java.nio.file.Files.write(new File(a[1]).toPath(), sb.toString().getBytes("UTF-8")); else System.out.print(sb); return;
        }
        if (a[0].equals("serve")) {
            List<String> pos = new ArrayList<>(); String host = "127.0.0.1"; boolean browser = true, workspaces = false, readOnly = false; int retention = 0;
            for (int i = 1; i < a.length; i++) { if (a[i].equals("--host") && i + 1 < a.length) host = a[++i]; else if (a[i].equals("--no-browser")) browser = false; else if (a[i].equals("--workspaces")) workspaces = true; else if (a[i].equals("--read-only-settings")) readOnly = true; else if (a[i].equals("--retention-days") && i + 1 < a.length) retention = Integer.parseInt(a[++i]); else pos.add(a[i]); }
            int port = pos.size() > 0 ? Integer.parseInt(pos.get(0)) : 8765; File data = new File(pos.size() > 1 ? pos.get(1) : "data"); File st = new File(System.getProperty("tca.static", "static"));
            if (!st.isDirectory()) { File jarDir = new File(Main.class.getProtectionDomain().getCodeSource().getLocation().getPath()).getParentFile(); st = new File(jarDir, "static"); if (!st.isDirectory()) st = new File(jarDir.getParentFile(), "static"); }
            new tca.web.WebServer(data, st, workspaces, retention, readOnly).start(host, port); String url = "http://" + (host.equals("0.0.0.0") ? "127.0.0.1" : host) + ":" + port + "/"; System.out.println("TWX Code Analyzer running at " + url + " (bound to " + host + ", data: " + data.getAbsolutePath() + ", static: " + st.getAbsolutePath() + ")");
            if (browser) try { if (java.awt.Desktop.isDesktopSupported()) java.awt.Desktop.getDesktop().browse(new java.net.URI(url)); } catch (Throwable t) { System.out.println("open " + url + " in a browser"); }
            return;
        }
        if (a[0].equals("analyze")) {
            long t0 = System.currentTimeMillis(); TwxModel m = TwxLoader.load(new File(a[1])); tca.rules.RuleSettings rs = new tca.rules.RuleSettings(); String out = null;
            for (int i = 2; i < a.length; i++) { if (a[i].equals("--settings") && i + 1 < a.length) rs = tca.rules.RuleSettings.fromJson(new String(java.nio.file.Files.readAllBytes(new File(a[++i]).toPath()), "UTF-8")); else if (a[i].equals("--toolkits")) rs.includeToolkits = true; else out = a[i]; }
            tca.engine.Analyzer an = new tca.engine.Analyzer(); rs.prune(an.rules()); for (String w : rs.warnings) System.out.println("settings: " + w);
            tca.engine.Report r = an.analyze(m, rs.toAnalyzerSettings()); String json = tca.util.Json.writePretty(r.toJson());
            if (System.getProperty("tca.profile") != null) { List<Map.Entry<String, Long>> ts = new ArrayList<>(an.ruleTimes.entrySet()); Collections.sort(ts, new Comparator<Map.Entry<String, Long>>() { public int compare(Map.Entry<String, Long> a, Map.Entry<String, Long> b) { return Long.compare(b.getValue(), a.getValue()); } }); for (int i = 0; i < Math.min(15, ts.size()); i++) System.out.println("  time " + ts.get(i).getValue() + " ms  " + ts.get(i).getKey()); }
            if (out != null) { java.nio.file.Files.write(new File(out).toPath(), json.getBytes("UTF-8")); }
            Map<String, Integer> bySev = new TreeMap<>(), byRule = new TreeMap<>(); for (tca.rules.Finding f : r.findings) { bySev.merge(f.severity, 1, Integer::sum); byRule.merge(f.ruleId + " " + f.title, 1, Integer::sum); }
            System.out.println(r.appName + " " + r.snapshotName + ": " + r.findings.size() + " findings " + bySev + " health=" + ((Map<?, ?>) r.toJson().get("summary")).get("healthScore") + (rs.isCustomized() ? " (custom rule settings)" : "") + " in " + (System.currentTimeMillis() - t0) + "ms");
            for (Map.Entry<String, Integer> e : byRule.entrySet()) System.out.println("  " + String.format("%5d", e.getValue()) + "  " + e.getKey());
            System.out.println("top findings:"); for (int i = 0; i < Math.min(12, r.findings.size()); i++) { tca.rules.Finding f = r.findings.get(i); System.out.println("  [" + f.severity + " " + f.score + "] " + f.ruleId + " " + f.path() + " :: " + f.message.replaceAll("\\s+", " ")); }
            return;
        }
        if (a[0].equals("inventory")) {
            long t0 = System.currentTimeMillis(); TwxModel m = TwxLoader.load(new File(a[1]));
            System.out.println(m.app.label() + " objects=" + m.app.objects.size() + " toolkits=" + m.toolkits.size() + " deps=" + m.app.dependencies.size() + " load=" + (System.currentTimeMillis() - t0) + "ms");
            System.out.println("  types: " + m.app.typeCounts());
            int items = 0, links = 0, scripts = 0, fos = 0, flows = 0, lanes = 0;
            for (TwxObject o : m.app.byType("process")) { ServiceModel s = ServiceParser.parse(o); items += s.items.size(); links += s.links.size(); scripts += Scripts.of(o, s, null, null).size(); }
            for (TwxObject o : m.app.byType("bpd")) { BpdModel b = BpdParser.parse(o); fos += b.flowObjects.size(); flows += b.flows.size(); lanes += b.lanes.size(); scripts += Scripts.of(o, null, b, null).size(); }
            for (TwxObject o : m.app.byType("coachView")) { CoachViewModel c = CoachViewParser.parse(o); scripts += Scripts.of(o, null, null, c).size(); }
            System.out.println("  services: items=" + items + " links=" + links + " | bpds: lanes=" + lanes + " flowObjects=" + fos + " flows=" + flows + " | scripts=" + scripts + " parse=" + (System.currentTimeMillis() - t0) + "ms");
            TwxObject first = m.app.byType("process").isEmpty() ? null : m.app.byType("process").get(0);
            if (first != null) { ServiceModel s = ServiceParser.parse(first); System.out.println("  sample service: " + s.name + " type=" + s.typeLabel() + " items=" + s.items.size() + " " + (s.items.isEmpty() ? "" : s.items.get(0).name + "@" + s.items.get(0).x + "," + s.items.get(0).y + " kind=" + s.items.get(0).kind())); }
            if (!m.app.byType("bpd").isEmpty()) { BpdModel b = BpdParser.parse(m.app.byType("bpd").get(0)); System.out.println("  sample bpd: " + b.name + " lanes=" + b.lanes.size() + " fo=" + b.flowObjects.size() + " flows=" + b.flows.size() + " first flow " + (b.flows.isEmpty() ? "" : b.flows.get(0).fromId + " -> " + b.flows.get(0).toId + " cond=" + b.flows.get(0).condition)); }
        }
    }
}
