package tca.enterprise;

import java.util.*;
import tca.engine.Analyzer;
import tca.util.Json;

/** OpenAPI 3.0 description of the HTTP API (served at /api/openapi.json, rendered by the bundled Swagger UI at swagger/). */
public final class OpenApi {
    private OpenApi() {}
    static Map<String, Object> op(String tag, String summary, String description, Object... more) { Map<String, Object> m = Json.obj("tags", Arrays.asList(tag), "summary", summary, "description", description, "responses", Json.obj("200", Json.obj("description", "OK"))); for (int i = 0; i + 1 < more.length; i += 2) m.put(String.valueOf(more[i]), more[i + 1]); return m; }
    static Map<String, Object> p(String name, String in, String type, String desc, boolean required) { return Json.obj("name", name, "in", in, "required", required, "description", desc, "schema", Json.obj("type", type)); }
    static Map<String, Object> jsonBody(Map<String, Object> schema) { return Json.obj("required", true, "content", Json.obj("application/json", Json.obj("schema", schema))); }
    static Map<String, Object> obj(Object... props) { Map<String, Object> ps = new LinkedHashMap<>(); for (int i = 0; i + 1 < props.length; i += 2) ps.put(String.valueOf(props[i]), Json.obj("type", props[i + 1])); return Json.obj("type", "object", "properties", ps); }
    static Map<String, Object> resp(String code, String desc) { return Json.obj(code, Json.obj("description", desc)); }
    static Map<String, Object> responses(Object... kv) { Map<String, Object> m = new LinkedHashMap<>(); for (int i = 0; i + 1 < kv.length; i += 2) m.put(String.valueOf(kv[i]), Json.obj("description", kv[i + 1])); return m; }

    public static Map<String, Object> document(EnterpriseApi.Config cfg) {
        Map<String, Object> paths = new LinkedHashMap<>();
        // CI / CD
        paths.put("/api/analyze", Json.obj("post", op("Analysis", "Analyze a TWX export", "Upload a .twx (multipart field `file`, or the raw file as the body with `name=`). Synchronous by default: the full report is returned when the analysis finishes. With `async=1` the analysis is queued and a job (HTTP 202) is returned; poll `/api/jobs/{id}` until `status` is `done`, then read `/api/report/{id}/verdict`. With `gate=1` (synchronous) the call answers 422 when the quality gate of the workspace policy fails.",
            "parameters", Arrays.asList(p("toolkits", "query", "string", "1 = also analyze the bundled non-system toolkits", false), p("name", "query", "string", "file name when the body is the raw file", false), p("async", "query", "string", "1 = queue the analysis and return a job", false), p("gate", "query", "string", "1 = answer 422 when the verdict is failed (synchronous only)", false), p("settings", "query", "string", "one-off rule setting overrides (settings file format, JSON)", false)),
            "requestBody", Json.obj("content", Json.obj("multipart/form-data", Json.obj("schema", Json.obj("type", "object", "properties", Json.obj("file", Json.obj("type", "string", "format", "binary")))), "application/octet-stream", Json.obj("schema", Json.obj("type", "string", "format", "binary")))),
            "responses", responses("200", "the report (findings, summary, gate, policy)", "202", "queued: the job", "413", "workspace quota exceeded", "422", "quality gate failed (gate=1)"))));
        paths.put("/api/jobs", Json.obj("get", op("Analysis", "Queued and recent analyses of the workspace", "Newest first, with queue position and progress.")));
        paths.put("/api/jobs/{id}", Json.obj("get", op("Analysis", "State of a queued analysis", "`status` is queued, running, done or failed; `progress` says where it is (rule n of m); `reportId` is set when done.", "parameters", Arrays.asList(p("id", "path", "string", "job id", true)), "responses", responses("200", "the job", "404", "unknown job"))));
        paths.put("/api/report/{id}/verdict", Json.obj("get", op("Analysis", "Quality gate verdict of a report", "HTTP 200 when the gate passed or no gate is configured (`verdict` = passed | no-gate), HTTP 422 when it failed. The body lists every check with its limit and actual value, the policy and the summary. Use it as the pass / fail step of a pipeline.", "parameters", Arrays.asList(p("id", "path", "string", "report id", true)), "responses", responses("200", "passed or no gate", "422", "failed", "404", "unknown report"))));
        paths.put("/api/report/{id}/summary", Json.obj("get", op("Analysis", "Summary of a report", "Application, health, counts by severity and category, gate, policy, coverage and inventory without the findings.", "parameters", Arrays.asList(p("id", "path", "string", "report id", true)))));
        paths.put("/api/report/{id}", Json.obj("get", op("Analysis", "Full report", "Inventory, summary, coverage, diagnostics, toolkit usage, rules, findings (with `accepted` flags), gate and policy.", "parameters", Arrays.asList(p("id", "path", "string", "report id", true))), "delete", op("Analysis", "Delete an analysis permanently", "Removes the uploaded file, the report and the metadata.", "parameters", Arrays.asList(p("id", "path", "string", "report id", true)))));
        paths.put("/api/report/{id}/pdf", Json.obj("get", op("Exports", "Findings report as PDF", "Same filters as the findings tab: sev, cat, rule, type, conf, q, sort.", "parameters", Arrays.asList(p("id", "path", "string", "report id", true)))));
        paths.put("/api/report/{id}/executive.pdf", Json.obj("get", op("Exports", "Executive summary as PDF", "One page: health, verdict, policy, trend, top risks, top rules.", "parameters", Arrays.asList(p("id", "path", "string", "report id", true)))));
        paths.put("/api/report/{id}/remediation", Json.obj("get", op("Analysis", "Findings grouped by artifact in fix order", "Open findings per artifact with the summed score and, when a designer link template is configured, the link to open the artifact.", "parameters", Arrays.asList(p("id", "path", "string", "report id", true)))));
        paths.put("/api/history", Json.obj("get", op("Analysis", "Analyses of the workspace", "Newest first: application, snapshot, health, findings, gate.")));
        paths.put("/api/compare", Json.obj("get", op("Analysis", "Compare two analyses", "Added / removed / changed artifacts and new / fixed findings between reports a and b.", "parameters", Arrays.asList(p("a", "query", "string", "older report id", true), p("b", "query", "string", "newer report id", true)))));
        paths.put("/api/objects/{id}", Json.obj("get", op("Artifacts", "Artifact tree of a report", "", "parameters", Arrays.asList(p("id", "path", "string", "report id", true), p("toolkits", "query", "string", "present = include toolkits", false)))));
        paths.put("/api/object/{id}/{objectId}", Json.obj("get", op("Artifacts", "Artifact detail", "Variables, steps, scripts, schema, references; `xml=1` adds the raw XML.", "parameters", Arrays.asList(p("id", "path", "string", "report id", true), p("objectId", "path", "string", "artifact id", true)))));
        paths.put("/api/search/{id}", Json.obj("get", op("Artifacts", "TWX search", "", "parameters", Arrays.asList(p("id", "path", "string", "report id", true), p("q", "query", "string", "text or regular expression", true), p("regex", "query", "string", "1 = regular expression", false), p("scope", "query", "string", "all | names | scripts | xml", false), p("types", "query", "string", "comma separated artifact types", false)))));
        paths.put("/api/toolkit-usage/{id}", Json.obj("get", op("Artifacts", "Toolkit usage", "", "parameters", Arrays.asList(p("id", "path", "string", "report id", true)))));
        // policies and settings
        paths.put("/api/rules", Json.obj("get", op("Policies", "Rule catalogue with the effective severity, impact and enabled state", "")));
        paths.put("/api/settings", Json.obj("get", op("Policies", "Rule settings in force for the workspace", "The settings file format; `download=1` sets a file name."), "put", op("Policies", "Import rule settings into the workspace", "Only when the workspace uses its own settings (policy `custom`).", "requestBody", jsonBody(Json.obj("type", "object"))), "delete", op("Policies", "Reset the workspace settings", "")));
        paths.put("/api/enterprise/policies", Json.obj("get", op("Policies", "Central rule policies", "Built-in entries `default` and `custom` plus the policies stored by administrators."), "post", op("Policies", "Create a policy (administrators)", "`settings` in the settings file format, `gates` = {healthMin, maxCritical, maxMajor, maxMinor, maxFindings, maxScore, rules{ruleId: max}}.", "requestBody", jsonBody(obj("id", "string", "name", "string", "description", "string", "settings", "object", "gates", "object")))));
        paths.put("/api/enterprise/policies/{id}", Json.obj("get", op("Policies", "A policy with its full settings document", "", "parameters", Arrays.asList(p("id", "path", "string", "policy id", true))), "put", op("Policies", "Update a policy (administrators)", "", "parameters", Arrays.asList(p("id", "path", "string", "policy id", true)), "requestBody", jsonBody(Json.obj("type", "object"))), "delete", op("Policies", "Delete a policy (administrators)", "", "parameters", Arrays.asList(p("id", "path", "string", "policy id", true)))));
        paths.put("/api/enterprise/workspace", Json.obj("get", op("Workspace", "Configuration of the current workspace", "Policy in force, gates, notifications, accepted findings count, storage."), "put", op("Workspace", "Configure the workspace", "`policy` = default | custom | policy id; `gates` (used with default / custom); `notify` = {webhook, emails[], onComplete, onGateFail}.", "requestBody", jsonBody(obj("policy", "string", "gates", "object", "notify", "object")))));
        paths.put("/api/enterprise/suppressions", Json.obj("get", op("Workspace", "Accepted findings (baseline)", "Keyed by finding key (`ruleId|objectType|objectName|itemName|location`)."), "put", op("Workspace", "Accept a finding", "Accepted findings stop counting in the score, health and verdict of every report of the workspace.", "requestBody", jsonBody(obj("key", "string", "reason", "string", "path", "string"))), "delete", op("Workspace", "Reopen a finding", "", "parameters", Arrays.asList(p("key", "query", "string", "finding key", true)))));
        paths.put("/api/enterprise/dashboard", Json.obj("get", op("Workspace", "Dashboard data", "Applications with their health trend, worst applications, most frequent rules, totals.")));
        paths.put("/api/enterprise/me", Json.obj("get", op("Workspace", "Who am I", "User, roles, workspace, teams and the features enabled on this server (same as /api/info).")));
        paths.put("/api/enterprise/teams", Json.obj("get", op("Administration", "Teams", ""), "post", op("Administration", "Create a team (administrators)", "", "requestBody", jsonBody(obj("id", "string", "name", "string", "description", "string", "members", "array", "admins", "array", "group", "string")))));
        paths.put("/api/enterprise/teams/{id}", Json.obj("put", op("Administration", "Update a team (administrators)", "", "parameters", Arrays.asList(p("id", "path", "string", "team id", true)), "requestBody", jsonBody(Json.obj("type", "object"))), "delete", op("Administration", "Delete a team (administrators)", "`purge=1` also deletes the team workspace.", "parameters", Arrays.asList(p("id", "path", "string", "team id", true), p("purge", "query", "string", "1 = delete the workspace files", false)))));
        paths.put("/api/enterprise/audit", Json.obj("get", op("Administration", "Audit trail (administrators)", "Newest first.", "parameters", Arrays.asList(p("limit", "query", "integer", "entries (default 200, max 5000)", false)))));
        paths.put("/api/enterprise/connections", Json.obj("get", op("Process Center", "Process Center definitions available to the caller", "The workspace's own definitions (scope workspace) and the shared ones stored by administrators (scope shared), without passwords."), "post", op("Process Center", "Store a connection (administrators)", "`designerUrl` = link template with {branchId}, {snapshotId}, {projectId}, {objectId}.", "requestBody", jsonBody(obj("id", "string", "name", "string", "url", "string", "user", "string", "password", "string", "designerUrl", "string")))));
        paths.put("/api/enterprise/workspace/connections", Json.obj("get", op("Process Center", "Process Center definitions saved in the workspace", "URL, user name and a stored password, saved by the user (personal workspace) or a team admin (team workspace); passwords are never returned."), "post", op("Process Center", "Save a Process Center definition in the workspace", "", "requestBody", jsonBody(obj("id", "string", "name", "string", "url", "string", "user", "string", "password", "string", "designerUrl", "string")))));
        paths.put("/api/enterprise/workspace/connections/{id}", Json.obj("put", op("Process Center", "Update a saved definition", "An empty password keeps the stored one.", "parameters", Arrays.asList(p("id", "path", "string", "definition id", true)), "requestBody", jsonBody(Json.obj("type", "object"))), "delete", op("Process Center", "Delete a saved definition", "", "parameters", Arrays.asList(p("id", "path", "string", "definition id", true)))));
        paths.put("/api/enterprise/connections/{id}/apps", Json.obj("get", op("Process Center", "Process applications and snapshots of a stored connection", "", "parameters", Arrays.asList(p("id", "path", "string", "connection id", true)))));
        paths.put("/api/enterprise/pc/apps", Json.obj("post", op("Process Center", "Process applications and snapshots with your own credentials", "", "requestBody", jsonBody(obj("url", "string", "user", "string", "password", "string")))));
        paths.put("/api/enterprise/pc/import", Json.obj("post", op("Process Center", "Export a snapshot from a Process Center and queue its analysis", "Process Center: `url` + `user` + `password`, or `connection` (stored; `url`, `user`, `password` given with it override the stored values). The snapshot: `snapshotId` (2064....), or `app` (acronym or name) + `snapshot` (name), or `app` + `track` (the tip of the track; default track when omitted). Optional `fileName`, `toolkits`. Returns the job (202); poll `/api/jobs/{id}`.", "requestBody", jsonBody(obj("connection", "string", "url", "string", "user", "string", "password", "string", "snapshotId", "string", "app", "string", "snapshot", "string", "track", "string", "fileName", "string", "toolkits", "boolean")), "responses", responses("202", "queued: the job", "404", "application or snapshot not found"))));
        paths.put("/api/enterprise/pc/evaluate", Json.obj("post", op("Process Center", "Evaluate a snapshot in one call (pipelines)", "Same body as pc/import, but synchronous: exports the snapshot, analyzes it with the workspace policy and answers with the verdict document - HTTP 200 when the quality gate passed or no gate is configured, HTTP 422 when it failed. Typical build step: `curl -f -H 'Authorization: Bearer ...' -d '{\"url\":\"https://pc:9443\",\"user\":\"ci\",\"password\":\"...\",\"app\":\"MYAPP\",\"snapshot\":\"1.4.0\"}' .../api/enterprise/pc/evaluate`. Large exports take minutes: raise the client timeout.", "requestBody", jsonBody(obj("connection", "string", "url", "string", "user", "string", "password", "string", "snapshotId", "string", "app", "string", "snapshot", "string", "track", "string", "toolkits", "boolean")), "responses", responses("200", "passed or no gate: the verdict with report id, checks, summary", "422", "failed: the same document", "404", "application or snapshot not found"))));
        // accounts
        if (cfg.auth.equals("builtin")) {
            paths.put("/api/auth/signup", Json.obj("post", op("Accounts", "Create an account", "Starts a session (cookie).", "requestBody", jsonBody(obj("email", "string", "name", "string", "password", "string")))));
            paths.put("/api/auth/login", Json.obj("post", op("Accounts", "Sign in", "Starts a session (cookie `tca_session`).", "requestBody", jsonBody(obj("email", "string", "password", "string")), "responses", responses("200", "signed in", "400", "unknown account or wrong password"))));
            paths.put("/api/auth/logout", Json.obj("post", op("Accounts", "Sign out", "")));
            paths.put("/api/auth/tokens", Json.obj("get", op("Accounts", "Personal access tokens", "Without the secret."), "post", op("Accounts", "Create a personal access token", "The token is returned once; use it as `Authorization: Bearer <token>` in pipelines.", "requestBody", jsonBody(obj("name", "string", "days", "integer")))));
            paths.put("/api/auth/tokens/{id}", Json.obj("delete", op("Accounts", "Revoke a token", "", "parameters", Arrays.asList(p("id", "path", "string", "token id", true)))));
            paths.put("/api/auth/password", Json.obj("post", op("Accounts", "Change the password", "", "requestBody", jsonBody(obj("old", "string", "password", "string")))));
            paths.put("/api/auth/purge", Json.obj("post", op("Accounts", "Delete every analysis of my workspace", "`settings: true` also removes the rule settings, accepted findings and workspace configuration.", "requestBody", jsonBody(obj("settings", "boolean")))));
            paths.put("/api/auth/account", Json.obj("delete", op("Accounts", "Delete my account and all its data", "", "requestBody", jsonBody(obj("password", "string")))));
            paths.put("/api/auth/users", Json.obj("get", op("Administration", "Accounts (administrators)", "")));
            paths.put("/api/auth/users/{id}", Json.obj("put", op("Administration", "Disable / enable an account or reset its password (administrators)", "", "parameters", Arrays.asList(p("id", "path", "string", "account id (e-mail)", true)), "requestBody", jsonBody(obj("disabled", "boolean", "password", "string"))), "delete", op("Administration", "Delete an account and its workspace (administrators)", "", "parameters", Arrays.asList(p("id", "path", "string", "account id (e-mail)", true)))));
        }
        paths.put("/api/auth/me", Json.obj("get", op("Accounts", "Who am I", "")));
        paths.put("/api/info", Json.obj("get", op("Server", "Server and deployment information", "Version, features, user and workspace of the caller.")));
        paths.put("/api/health", Json.obj("get", op("Server", "Health", "Liveness for load balancers: status, version, uptime, queue.")));
        paths.put("/api/metrics", Json.obj("get", op("Server", "Metrics (Prometheus text format)", "Analyses, failures, analysis time, uploads, requests, queue, stored reports, storage, workspaces, uptime.")));
        Map<String, Object> security = Json.obj("bearerToken", Json.obj("type", "http", "scheme", "bearer", "description", "Personal access token (Accounts > tokens)"), "sessionCookie", Json.obj("type", "apiKey", "in", "cookie", "name", "tca_session"));
        return Json.obj("openapi", "3.0.3", "info", Json.obj("title", cfg.title + " API", "version", Analyzer.VERSION, "description", "Static analysis of IBM BPM / BAW TWX exports. Pipeline recipes: (1) `POST /api/enterprise/pc/evaluate` with the Process Center URL, credentials, application and snapshot name - export, analysis and verdict in one call (HTTP 422 = quality gate failed); (2) `POST /api/analyze?gate=1` with the export file - analysis and verdict in one call; (3) `POST /api/analyze?async=1`, poll `GET /api/jobs/{id}` until done, then `GET /api/report/{id}/verdict`. Authenticate with a personal access token (`Authorization: Bearer ...`), the session cookie of the browser, or the container's security. Workspace selection for team members: cookie or header `X-TCA-Workspace: team:<id>`."),
                "servers", Arrays.asList(Json.obj("url", "..", "description", "this deployment")), "tags", Arrays.asList(Json.obj("name", "Analysis"), Json.obj("name", "Exports"), Json.obj("name", "Artifacts"), Json.obj("name", "Policies"), Json.obj("name", "Workspace"), Json.obj("name", "Process Center"), Json.obj("name", "Accounts"), Json.obj("name", "Administration"), Json.obj("name", "Server")),
                "components", Json.obj("securitySchemes", security), "security", Arrays.asList(Json.obj("bearerToken", new ArrayList<Object>()), Json.obj("sessionCookie", new ArrayList<Object>())), "paths", paths);
    }
}
