/* TWX Code Analyzer - enterprise layer of the web application (WAR). Loaded by app.js only when the server reports enterprise features:
   accounts, workspaces and teams, dashboard, queued analyses, policies with quality gates, accepted findings, remediation view,
   Process Center import, executive summary, notifications, audit, users, API documentation and help. Registers pages, report tabs and hooks on window.TCA. */
(function () {
  var T = window.TCA, esc = T.esc, api = T.api, nav = T.nav, sevBadge = T.sevBadge, fmtBytes = T.fmtBytes, modal = T.modal, state = T.state, app = T.app;
  function info() { return T.info(); }
  function post(path, body, method) { return api(path, { method: method || 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body || {}) }); }
  function del(path, body) { return api(path, { method: 'DELETE', headers: { 'Content-Type': 'application/json' }, body: body ? JSON.stringify(body) : undefined }); }
  function alertBox(kind, html) { return '<div class="alert alert-' + kind + ' py-2 small">' + html + '</div>'; }
  function msg(id, text, cls) { var m = document.getElementById(id); if (m) { m.className = 'small ms-2 ' + (cls || 'text-success'); m.textContent = text; } }
  function refreshInfo() { return api('api/info').then(function (i) { T.setInfo(i); buildNav(); return i; }); }
  function helpLink(anchor) { return '<a class="small ms-2" href="#/help/' + anchor + '" title="Help"><i class="fa-regular fa-circle-question"></i></a>'; }
  function gateBadge(g) { if (!g || g.passed === null || g.passed === undefined) return '<span class="badge bg-secondary" title="No quality gate configured">no gate</span>'; return g.passed ? '<span class="badge bg-success"><i class="fa-solid fa-check me-1"></i>gate passed</span>' : '<span class="badge bg-danger"><i class="fa-solid fa-xmark me-1"></i>gate failed</span>'; }
  function healthCls(h) { return h >= 80 ? 'text-success' : h >= 50 ? 'text-warning' : 'text-danger'; }
  function setScope(v) { document.cookie = 'tca_scope=' + v + '; Path=/; Max-Age=31536000; SameSite=Lax'; }

  // ---------------- navigation ----------------
  function buildNav() {
    var i = info(), f = i.features || {}, w = i.workspace || {};
    var items = [['#/', 'home', 'fa-gauge-high', 'Dashboard'], ['#/analyze', 'analyze', 'fa-upload', 'Analyze'], ['#/history', 'history', 'fa-clock-rotate-left', 'History'], ['#/compare', 'compare', 'fa-code-compare', 'Compare'], ['#/rules', 'rules', 'fa-list-check', 'Rules'], ['#/settings', 'settings', 'fa-sliders', 'Settings']];
    if (f.processCenter) items.push(['#/processcenter', 'processcenter', 'fa-server', 'Process Center']);
    if (i.admin) items.push(['#/admin', 'admin', 'fa-user-shield', 'Administration']);
    items.push(['#/help', 'help', 'fa-circle-question', 'Help']);
    document.getElementById('mainnav').innerHTML = items.map(function (x) { return '<li class="nav-item"><a class="nav-link" href="' + x[0] + '" data-nav="' + x[1] + '"><i class="fa-solid ' + x[2] + ' me-1"></i>' + x[3] + '</a></li>'; }).join('') +
      '<li class="nav-item"><a class="nav-link" href="swagger/index.html" target="_blank" title="OpenAPI description and Swagger UI"><i class="fa-solid fa-plug me-1"></i>API</a></li>';
    var right = '';
    if (i.user) {
      var teams = i.teams || [];
      right += '<div class="dropdown d-inline-block me-2"><button class="btn btn-sm btn-outline-light dropdown-toggle" data-bs-toggle="dropdown"><i class="fa-solid ' + (w.kind === 'team' ? 'fa-people-group' : 'fa-folder') + ' me-1"></i>' + esc(w.label || 'workspace') + '</button><ul class="dropdown-menu dropdown-menu-end"><li><h6 class="dropdown-header">Workspace</h6></li>' +
        '<li><a class="dropdown-item' + (w.kind === 'personal' ? ' active' : '') + '" href="#" data-scope="personal"><i class="fa-solid fa-folder me-1"></i>Personal</a></li>' + teams.map(function (t) { return '<li><a class="dropdown-item' + (w.kind === 'team' && w.id === t.id ? ' active' : '') + '" href="#" data-scope="team:' + esc(t.id) + '"><i class="fa-solid fa-people-group me-1"></i>' + esc(t.name) + (t.admin ? ' <span class="badge bg-info text-dark">admin</span>' : '') + '</a></li>'; }).join('') + (teams.length ? '' : '<li><span class="dropdown-item-text small text-muted">No teams yet</span></li>') + '</ul></div>';
      right += '<div class="dropdown d-inline-block"><button class="btn btn-sm btn-outline-light dropdown-toggle" data-bs-toggle="dropdown"><i class="fa-solid fa-user me-1"></i>' + esc(i.name || i.user) + (i.admin ? ' <span class="badge bg-warning text-dark">admin</span>' : '') + '</button><ul class="dropdown-menu dropdown-menu-end"><li><a class="dropdown-item" href="#/account"><i class="fa-solid fa-id-card me-1"></i>Account</a></li><li><a class="dropdown-item" href="#/jobs"><i class="fa-solid fa-list-ol me-1"></i>Queue</a></li>' + (i.auth === 'builtin' && i.source === 'session' ? '<li><hr class="dropdown-divider"></li><li><a class="dropdown-item" href="#" id="navLogout"><i class="fa-solid fa-right-from-bracket me-1"></i>Sign out</a></li>' : '') + '</ul></div>';
    } else if (i.auth === 'builtin') {
      right += '<a class="btn btn-sm btn-outline-light me-2" href="#/login"><i class="fa-solid fa-right-to-bracket me-1"></i>Sign in</a>' + (i.signup ? '<a class="btn btn-sm btn-light" href="#/signup">Sign up</a>' : '');
    }
    document.getElementById('navright').innerHTML = right;
    document.querySelectorAll('#navright [data-scope]').forEach(function (a) { a.addEventListener('click', function (e) { e.preventDefault(); setScope(a.getAttribute('data-scope')); refreshInfo().then(function () { T.route(); }); }); });
    var lo = document.getElementById('navLogout'); if (lo) lo.addEventListener('click', function (e) { e.preventDefault(); post('api/auth/logout').then(function () { setScope('personal'); refreshInfo().then(function () { nav('#/'); T.route(); }); }); });
    if (i.title && i.title !== 'TWX Code Analyzer') document.querySelector('.navbar-brand').lastChild.textContent = i.title;
  }
  function requireUser() { if (info().user) return true; app.innerHTML = alertBox('warning', 'Sign in to use this page.') + (info().auth === 'builtin' ? '<a class="btn btn-primary btn-sm" href="#/login">Sign in</a> ' + (info().signup ? '<a class="btn btn-outline-primary btn-sm" href="#/signup">Sign up</a>' : '') : ''); return false; }
  function requireAdmin() { if (!requireUser()) return false; if (info().admin) return true; app.innerHTML = alertBox('warning', 'Administrators only. Administrators are designated in the admins properties file of the server.'); return false; }

  // ---------------- accounts ----------------
  function loginPage() {
    T.setNav(''); app.innerHTML = '<div class="row justify-content-center"><div class="col-md-5"><div class="card p-4"><h4>Sign in</h4><div class="small-muted mb-3">Signed-in users keep their analyses, rule settings and accepted findings across sessions and browsers.</div>' +
      '<div class="mb-2"><label class="form-label small">E-mail</label><input class="form-control" id="lEmail" type="email" autocomplete="username"></div><div class="mb-3"><label class="form-label small">Password</label><input class="form-control" id="lPw" type="password" autocomplete="current-password"></div>' +
      '<button class="btn btn-primary" id="lGo">Sign in</button> ' + (info().signup ? '<a class="btn btn-link" href="#/signup">Create an account</a>' : '') + '<div id="lMsg" class="small text-danger mt-2"></div></div></div></div>';
    function go() { post('api/auth/login', { email: document.getElementById('lEmail').value, password: document.getElementById('lPw').value }).then(function () { setScope('personal'); return refreshInfo(); }).then(function () { nav('#/'); }).catch(function (e) { document.getElementById('lMsg').textContent = String(e.message || e); }); }
    document.getElementById('lGo').addEventListener('click', go); document.getElementById('lPw').addEventListener('keydown', function (e) { if (e.key === 'Enter') go(); });
  }
  function signupPage() {
    T.setNav(''); if (!info().signup) { app.innerHTML = alertBox('warning', 'Sign-up is disabled on this server.'); return; }
    app.innerHTML = '<div class="row justify-content-center"><div class="col-md-5"><div class="card p-4"><h4>Create an account</h4><div class="small-muted mb-3">Your analyses stay in your private workspace until you delete them. You can purge everything or delete the account at any time from the Account page.</div>' +
      '<div class="mb-2"><label class="form-label small">Name</label><input class="form-control" id="sName"></div><div class="mb-2"><label class="form-label small">E-mail</label><input class="form-control" id="sEmail" type="email" autocomplete="username"></div><div class="mb-3"><label class="form-label small">Password (8 characters or more)</label><input class="form-control" id="sPw" type="password" autocomplete="new-password"></div>' +
      '<button class="btn btn-primary" id="sGo">Sign up</button> <a class="btn btn-link" href="#/login">I have an account</a><div id="sMsg" class="small text-danger mt-2"></div></div></div></div>';
    document.getElementById('sGo').addEventListener('click', function () { post('api/auth/signup', { name: document.getElementById('sName').value, email: document.getElementById('sEmail').value, password: document.getElementById('sPw').value }).then(function () { setScope('personal'); return refreshInfo(); }).then(function () { nav('#/'); }).catch(function (e) { document.getElementById('sMsg').textContent = String(e.message || e); }); });
  }
  function accountPage() {
    T.setNav(''); if (!requireUser()) return; var i = info();
    app.innerHTML = '<h4>Account' + helpLink('accounts') + '</h4><div class="row g-3"><div class="col-lg-6">' +
      '<div class="card p-3 mb-3"><h6>Profile</h6><table class="table table-sm mb-0"><tr><td>User</td><td>' + esc(i.user) + '</td></tr><tr><td>Name</td><td>' + esc(i.name) + '</td></tr><tr><td>Role</td><td>' + (i.admin ? 'administrator' : 'user') + '</td></tr><tr><td>Signed in through</td><td>' + esc(i.source) + '</td></tr></table></div>' +
      (i.auth === 'builtin' ? '<div class="card p-3 mb-3"><h6>Change password</h6><input class="form-control form-control-sm mb-2" id="pOld" type="password" placeholder="current password"><input class="form-control form-control-sm mb-2" id="pNew" type="password" placeholder="new password (8+ characters)"><button class="btn btn-sm btn-primary" id="pGo">Change</button><span id="pMsg" class="small ms-2"></span></div>' : '') +
      '<div class="card p-3 mb-3 border-danger"><h6 class="text-danger">Data</h6><div class="small-muted mb-2">Your analyses are kept until you delete them. Purge removes every analysis of your personal workspace permanently; deleting the account also removes settings, accepted findings, tokens and the account itself.</div>' +
      '<button class="btn btn-sm btn-outline-danger" id="purgeGo"><i class="fa-solid fa-broom me-1"></i>Purge all my analyses</button> <label class="small ms-2"><input type="checkbox" id="purgeSettings"> also settings and accepted findings</label>' + (i.auth === 'builtin' ? '<div class="mt-3"><input class="form-control form-control-sm d-inline-block w-auto me-2" id="delPw" type="password" placeholder="password"><button class="btn btn-sm btn-danger" id="delGo"><i class="fa-solid fa-user-xmark me-1"></i>Delete my account</button></div>' : '') + '<div id="dMsg" class="small mt-2"></div></div></div>' +
      '<div class="col-lg-6">' + ((i.features || {}).tokens ? '<div class="card p-3 mb-3"><h6>Personal access tokens</h6><div class="small-muted mb-2">For pipelines and scripts: send <code>Authorization: Bearer &lt;token&gt;</code>. The token is shown once when created. See the <a href="swagger/index.html" target="_blank">API documentation</a> and <a href="#/help/cicd">CI / CD integration</a>.</div><div id="tokens">Loading...</div><div class="mt-2"><input class="form-control form-control-sm d-inline-block w-auto me-1" id="tName" placeholder="name (e.g. jenkins)"><input class="form-control form-control-sm d-inline-block me-1" style="width:90px" id="tDays" type="number" value="365" title="valid for days"><button class="btn btn-sm btn-primary" id="tGo">Create token</button></div><div id="tNew" class="mt-2"></div></div>' : '') + '</div></div>';
    if (document.getElementById('pGo')) document.getElementById('pGo').addEventListener('click', function () { post('api/auth/password', { old: document.getElementById('pOld').value, password: document.getElementById('pNew').value }).then(function () { msg('pMsg', 'Password changed.'); }).catch(function (e) { msg('pMsg', String(e.message || e), 'text-danger'); }); });
    document.getElementById('purgeGo').addEventListener('click', function () { if (!confirm('Delete every analysis of your personal workspace permanently?')) return; post('api/auth/purge', { settings: document.getElementById('purgeSettings').checked }).then(function (r) { msg('dMsg', r.deleted + ' analysis(es) deleted.'); }).catch(function (e) { msg('dMsg', String(e.message || e), 'text-danger'); }); });
    if (document.getElementById('delGo')) document.getElementById('delGo').addEventListener('click', function () { if (!confirm('Delete your account and all its data permanently?')) return; del('api/auth/account', { password: document.getElementById('delPw').value }).then(function () { setScope('personal'); return refreshInfo(); }).then(function () { nav('#/'); }).catch(function (e) { msg('dMsg', String(e.message || e), 'text-danger'); }); });
    function tokens() { api('api/auth/tokens').then(function (l) { document.getElementById('tokens').innerHTML = l.length ? '<table class="table table-sm mb-0"><thead><tr><th>Name</th><th>Created</th><th>Expires</th><th>Last used</th><th></th></tr></thead><tbody>' + l.map(function (t) { return '<tr><td>' + esc(t.name) + '</td><td>' + esc(t.createdAt) + '</td><td>' + esc(t.expiresAt || 'never') + '</td><td>' + esc(t.lastUsed || '-') + '</td><td class="text-end"><button class="btn btn-sm btn-outline-danger" data-tok="' + esc(t.id) + '"><i class="fa-solid fa-trash"></i></button></td></tr>'; }).join('') + '</tbody></table>' : '<div class="small-muted">No tokens.</div>'; document.querySelectorAll('[data-tok]').forEach(function (b) { b.addEventListener('click', function () { del('api/auth/tokens/' + b.getAttribute('data-tok')).then(tokens); }); }); }).catch(function () {}); }
    if (document.getElementById('tGo')) { tokens(); document.getElementById('tGo').addEventListener('click', function () { post('api/auth/tokens', { name: document.getElementById('tName').value, days: +document.getElementById('tDays').value }).then(function (t) { document.getElementById('tNew').innerHTML = alertBox('success', 'Token <b>' + esc(t.name) + '</b> created. Copy it now, it is not shown again:<div class="mono mt-1 user-select-all">' + esc(t.token) + '</div>'); tokens(); }).catch(function (e) { document.getElementById('tNew').innerHTML = alertBox('danger', esc(e.message || e)); }); }); }
  }

  // ---------------- dashboard ----------------
  function dashboard() {
    T.setNav('home'); document.getElementById('current-report').textContent = ''; var i = info();
    app.innerHTML = '<div class="d-flex align-items-center mb-2"><h4 class="mb-0">Dashboard <span class="text-secondary fs-6">' + esc((i.workspace || {}).label || '') + '</span>' + helpLink('dashboard') + '</h4><span class="ms-auto"><a class="btn btn-primary btn-sm" href="#/analyze"><i class="fa-solid fa-upload me-1"></i>Analyze an export</a></span></div>' + (i.demo && !i.user ? alertBox('info', '<i class="fa-solid fa-flask me-1"></i>Demo mode: this browser has a private, temporary workspace. <a href="#/signup">Create an account</a> to keep your analyses, use policies, quality gates and the API.') : '') + '<div id="dash">Loading...</div>';
    api('api/enterprise/dashboard').then(function (d) {
      var t = d.totals; if (!t.analyses) { document.getElementById('dash').innerHTML = '<div class="card p-4 text-center"><div class="mb-2">No analyses in this workspace yet.</div><a class="btn btn-primary" href="#/analyze">Analyze a TWX export</a></div>'; return; }
      var html = '<div class="row g-3">' + [['Applications', t.applications, ''], ['Analyses', t.analyses, ''], ['Average health', t.averageHealth === null ? '-' : t.averageHealth, healthCls(t.averageHealth)], ['Gate failures', t.gateFailures, t.gateFailures ? 'text-danger' : 'text-success'], ['Storage', fmtBytes(t.bytes), '']].map(function (x) { return '<div class="col-6 col-lg"><div class="card p-3 text-center"><div class="stat ' + x[2] + '">' + x[1] + '</div><div class="small-muted">' + x[0] + '</div></div></div>'; }).join('') + '</div>' +
        '<div class="row g-3 mt-1"><div class="col-lg-8"><div class="card p-3"><h6>Applications</h6><table class="table table-sm table-hover mb-0"><thead><tr><th>Application</th><th>Latest snapshot</th><th class="text-end">Health</th><th class="text-end">Change</th><th class="text-end">Open findings</th><th>Gate</th><th style="width:140px">Trend</th><th class="text-end">Analyses</th></tr></thead><tbody>' +
        d.applications.map(function (a, k) { var l = a.latest; return '<tr class="selectable" onclick="location.hash=\'#/report/' + l.id + '\'"><td><b>' + esc(a.name) + '</b> <span class="small-muted">' + esc(a.acronym) + '</span></td><td>' + esc(l.snapshot) + ' <span class="small-muted">' + esc(l.analyzedAt) + '</span></td><td class="text-end"><b class="' + healthCls(l.health) + '">' + l.health + '</b></td><td class="text-end">' + (a.delta === null ? '<span class="small-muted">first</span>' : a.delta > 0 ? '<span class="text-success">+' + a.delta + '</span>' : a.delta < 0 ? '<span class="text-danger">' + a.delta + '</span>' : '0') + '</td><td class="text-end">' + l.findings + '</td><td>' + gateBadge({ passed: l.gate }) + '</td><td><canvas id="spark' + k + '" height="30"></canvas></td><td class="text-end">' + a.analyses + '</td></tr>'; }).join('') + '</tbody></table></div></div>' +
        '<div class="col-lg-4"><div class="card p-3 mb-3"><h6>Needs attention</h6><table class="table table-sm mb-0"><tbody>' + d.worst.slice(0, 5).map(function (a) { return '<tr class="selectable" onclick="location.hash=\'#/report/' + a.latest.id + '\'"><td>' + esc(a.name) + '</td><td class="text-end"><b class="' + healthCls(a.latest.health) + '">' + a.latest.health + '</b></td><td>' + gateBadge({ passed: a.latest.gate }) + '</td></tr>'; }).join('') + '</tbody></table></div>' +
        '<div class="card p-3"><h6>Most frequent rules (latest analyses)</h6><table class="table table-sm mb-0"><tbody>' + d.topRules.map(function (r) { return '<tr><td><b>' + esc(r.id) + '</b> <span class="small">' + esc(r.title) + '</span></td><td>' + sevBadge(r.severity) + '</td><td class="text-end">' + r.count + '</td></tr>'; }).join('') + '</tbody></table></div></div></div>' +
        '<div class="card p-3 mt-3"><h6>Recent analyses</h6>' + T.historyTable(d.recent) + '</div>';
      document.getElementById('dash').innerHTML = html;
      d.applications.forEach(function (a, k) { var c = document.getElementById('spark' + k); if (!c || !window.Chart) return; new Chart(c, { type: 'line', data: { labels: a.series.map(function (p) { return p.snapshot; }), datasets: [{ data: a.series.map(function (p) { return p.health; }), borderColor: '#0d6efd', borderWidth: 1.5, pointRadius: 2, fill: false, tension: 0.3 }] }, options: { animation: false, plugins: { legend: { display: false }, tooltip: { enabled: true } }, scales: { x: { display: false }, y: { display: false, min: 0, max: 100 } } } }); });
      document.querySelectorAll('#dash [data-del]').forEach(function (b) { b.addEventListener('click', function (e) { e.stopPropagation(); T.deleteReport(b.getAttribute('data-del'), dashboard); }); });
    }).catch(function (e) { document.getElementById('dash').innerHTML = alertBox('danger', esc(e.message || e)); });
  }

  // ---------------- analyze page with the queue ----------------
  function analyzePage() {
    T.setNav('analyze'); document.getElementById('current-report').textContent = '';
    app.innerHTML = '<div class="row justify-content-center"><div class="col-lg-8"><h4 class="mb-3">Analyze a TWX export' + helpLink('analyze') + '</h4>' + T.uploadHtml() + '<div class="mt-3" id="jobs"></div><div class="mt-4" id="recent"></div></div></div>';
    T.bindUpload(); renderJobs(); api('api/history').then(function (h) { var el = document.getElementById('recent'); if (!el || !h.length) return; el.innerHTML = '<h6>Recent analyses</h6>' + T.historyTable(h.slice(0, 8)); el.querySelectorAll('[data-del]').forEach(function (b) { b.addEventListener('click', function () { T.deleteReport(b.getAttribute('data-del'), analyzePage); }); }); });
  }
  var pollTimer = null;
  function renderJobs() {
    var el = document.getElementById('jobs'); if (!el) { if (pollTimer) { clearTimeout(pollTimer); pollTimer = null; } return; }
    api('api/jobs').then(function (l) { var active = l.filter(function (j) { return j.status === 'queued' || j.status === 'running'; });
      el.innerHTML = l.length ? '<div class="card p-2"><h6 class="mb-1">Queue</h6><table class="table table-sm mb-0"><tbody>' + l.slice(0, 6).map(function (j) { return '<tr><td>' + esc(j.fileName) + ' <span class="small-muted">' + fmtBytes(j.size) + (j.source !== 'upload' ? ' · ' + esc(j.source) : '') + '</span></td><td>' + (j.status === 'queued' ? '<span class="badge bg-secondary">queued #' + j.position + '</span>' : j.status === 'running' ? '<span class="spinner-border spinner-border-sm me-1"></span>' + esc(j.progress) : j.status === 'done' ? '<a href="#/report/' + esc(j.reportId) + '" class="badge bg-success text-decoration-none">done - open report</a>' : '<span class="badge bg-danger" title="' + esc(j.error) + '">failed</span> <span class="small text-danger">' + esc(j.error) + '</span>') + '</td></tr>'; }).join('') + '</tbody></table></div>' : '';
      if (active.length) pollTimer = setTimeout(renderJobs, 1500); else pollTimer = null; }).catch(function () { pollTimer = null; });
  }
  T.hooks.upload = function (file) {
    var lim = (info().features || {}).maxUploadMb; if (lim && file.size > lim * 1024 * 1024) { var p0 = document.getElementById('progress'); if (p0) p0.innerHTML = alertBox('danger', 'The file is ' + fmtBytes(file.size) + '; this server accepts uploads up to ' + lim + ' MB.'); return true; }
    var fd = new FormData(); fd.append('file', file); var tk = document.getElementById('optToolkits') && document.getElementById('optToolkits').checked ? '1' : '0'; var pr = document.getElementById('progress');
    if (pr) pr.innerHTML = alertBox('info', '<span class="spinner-border spinner-border-sm me-2"></span>Uploading <b>' + esc(file.name) + '</b> (' + fmtBytes(file.size) + ') ...');
    fetch('api/analyze?async=1&toolkits=' + tk + '&name=' + encodeURIComponent(file.name), { method: 'POST', body: fd }).then(function (r) { return r.json(); }).then(function (job) {
      if (job.error) { if (pr) pr.innerHTML = alertBox('danger', esc(job.error)); return; }
      function poll() { api('api/jobs/' + job.id).then(function (j) { if (!document.getElementById('progress')) return; if (j.status === 'done') { document.getElementById('progress').innerHTML = ''; state.id = null; nav('#/report/' + j.reportId); return; } if (j.status === 'failed') { document.getElementById('progress').innerHTML = alertBox('danger', 'Analysis failed: ' + esc(j.error)); renderJobs(); return; } document.getElementById('progress').innerHTML = alertBox('info', '<span class="spinner-border spinner-border-sm me-2"></span>' + (j.status === 'queued' ? 'Queued (position ' + j.position + ')' : 'Analyzing <b>' + esc(j.fileName) + '</b>: ' + esc(j.progress)) + ' ...'); setTimeout(poll, 1000); }).catch(function (e) { if (document.getElementById('progress')) document.getElementById('progress').innerHTML = alertBox('danger', esc(e.message || e)); }); }
      poll(); renderJobs();
    }).catch(function (e) { if (pr) pr.innerHTML = alertBox('danger', esc(e.message || e)); });
    return true;
  };
  function jobsPage() { T.setNav(''); app.innerHTML = '<h4>Analysis queue' + helpLink('analyze') + '</h4><div id="jobs">Loading...</div>'; renderJobs(); }

  // ---------------- report: header, verdict, remediation, acceptance ----------------
  T.hooks.reportHeader = function (r) { return '<span class="ms-3">' + gateBadge(r.gate) + (r.policy ? ' <span class="badge bg-light text-dark border" title="Rule policy used">' + esc(r.policy.name) + (r.policy.version ? ' v' + r.policy.version : '') + '</span>' : '') + '</span>' + '<a class="btn btn-sm btn-outline-secondary ms-3" href="api/report/' + esc(r.id) + '/executive.pdf" target="_blank" title="One-page management summary"><i class="fa-solid fa-file-pdf me-1"></i>Executive PDF</a>'; };
  T.hooks.afterReportHeader = function (r) {
    if (!r.gate || !r.gate.checks || !r.gate.checks.length) return; var tabDiv = document.getElementById('tab'); var box = document.createElement('div'); box.className = 'alert py-2 small ' + (r.gate.passed ? 'alert-success' : 'alert-danger');
    box.innerHTML = '<i class="fa-solid ' + (r.gate.passed ? 'fa-check' : 'fa-xmark') + ' me-1"></i><b>Quality gate ' + (r.gate.passed ? 'passed' : 'failed') + '</b> (' + esc(r.policy ? r.policy.name : '') + '): ' + r.gate.checks.map(function (c) { return esc(c.label) + ' ' + c.limit + ' (actual ' + c.actual + ') ' + (c.passed ? '<i class="fa-solid fa-check text-success"></i>' : '<i class="fa-solid fa-xmark text-danger"></i>'); }).join(' · ') + ' <a class="ms-2" href="api/report/' + esc(r.id) + '/verdict" target="_blank">verdict JSON</a>';
    tabDiv.parentNode.insertBefore(box, tabDiv);
  };
  T.reportTabs.push(['remediation', 'Remediation', 'fa-list-check', function () {
    var el = document.getElementById('tab'); el.innerHTML = 'Loading...';
    api('api/report/' + state.id + '/remediation').then(function (d) {
      if (!d.artifacts.length) { el.innerHTML = alertBox('success', 'No open findings.'); return; }
      el.innerHTML = '<div class="small-muted mb-2">Open findings grouped by artifact in fix order: the artifact with the highest weighted score comes first. Accepted findings are not shown.' + (d.designerTemplate ? '' : ' Configure a designer link template (Process Center connection or server setting) to open artifacts in Process Designer.') + helpLink('remediation') + '</div>' +
        d.artifacts.map(function (a) { return '<div class="card p-3 mb-2"><div class="d-flex align-items-center"><span class="badge bg-dark me-2">' + a.order + '</span><b>' + esc(a.objectTypeLabel || '') + ' ' + esc(a.objectName) + '</b><span class="small-muted ms-2">' + esc(a.package) + (a.toolkit ? ' (toolkit)' : '') + '</span><span class="ms-auto"><span class="score-pill">score ' + a.score + '</span> ' + Object.keys(a.bySeverity).map(function (s) { return sevBadge(s) + ' ' + a.bySeverity[s]; }).join(' ') + (a.objectId && state.report.uploadKept !== false ? ' <a class="btn btn-sm btn-outline-primary ms-2" href="#/report/' + state.id + '/objects/' + encodeURIComponent(a.objectId) + '"><i class="fa-solid fa-diagram-project"></i></a>' : '') + (a.designerUrl ? ' <a class="btn btn-sm btn-outline-secondary ms-1" href="' + esc(a.designerUrl) + '" target="_blank" title="Open in Process Designer"><i class="fa-solid fa-arrow-up-right-from-square"></i></a>' : '') + '</span></div>' +
          '<table class="table table-sm findings-table mt-2 mb-0"><tbody>' + a.findings.map(function (f) { return '<tr class="selectable" data-key="' + esc(f.key) + '"><td style="width:120px">' + sevBadge(f.severity) + ' <span class="score-pill">' + f.score + '</span></td><td><b>' + esc(f.ruleId) + '</b> ' + esc(f.title) + (f.itemName ? '<div class="small-muted">' + esc(f.itemName) + (f.line ? ' line ' + f.line : '') + '</div>' : '') + '</td><td>' + esc(f.message) + '<div class="small text-success"><i class="fa-solid fa-wrench me-1"></i>' + esc(f.remediation) + '</div></td></tr>'; }).join('') + '</tbody></table></div>'; }).join('');
      el.querySelectorAll('tr[data-key]').forEach(function (tr) { tr.addEventListener('click', function () { var f = state.report.findings.filter(function (x) { return x.key === tr.getAttribute('data-key'); })[0]; if (f) T.findingDetail(f); }); });
    }).catch(function (e) { el.innerHTML = alertBox('danger', esc(e.message || e)); });
  }]);
  T.hooks.findingDetail = function (x) { var w = info().workspace || {}; if (!w.manage || !x.key) return ''; return x.accepted ? '<button class="btn btn-outline-secondary btn-sm" id="btnUnaccept"><i class="fa-solid fa-rotate-left me-1"></i>Reopen finding</button>' : '<button class="btn btn-outline-success btn-sm" id="btnAccept"><i class="fa-solid fa-check me-1"></i>Accept finding</button>'; };
  T.hooks.findingDetailBind = function (x) {
    var a = document.getElementById('btnAccept'), u = document.getElementById('btnUnaccept');
    function reload() { bootstrap.Modal.getInstance(document.getElementById('detailModal')).hide(); var id = state.id; state.id = null; state.report = null; nav('#/report/' + id + '/findings'); T.route(); }
    if (a) a.addEventListener('click', function () { var reason = prompt('Why is this finding accepted (false positive, planned, risk accepted ...)? The reason is recorded with your name.'); if (reason === null) return; post('api/enterprise/suppressions', { key: x.key, reason: reason, path: x.path }, 'PUT').then(reload).catch(function (e) { alert(e.message || e); }); });
    if (u) u.addEventListener('click', function () { del('api/enterprise/suppressions?key=' + encodeURIComponent(x.key)).then(reload).catch(function (e) { alert(e.message || e); }); });
  };

  // ---------------- settings: policy selection, gates, notifications, workspace settings ----------------
  function gatesForm(g, dis) {
    g = g || {}; var fields = [['healthMin', 'Health score at least'], ['maxCritical', 'Critical findings at most'], ['maxMajor', 'Major findings at most'], ['maxMinor', 'Minor findings at most'], ['maxFindings', 'Open findings at most'], ['maxScore', 'Weighted score at most']];
    return '<div class="form-check mb-2"><input class="form-check-input" type="checkbox" id="gEnabled"' + (g.enabled === false ? '' : ' checked') + dis + '><label class="form-check-label" for="gEnabled">Quality gate enabled</label></div><div class="row g-2">' + fields.map(function (f) { return '<div class="col-md-6"><label class="form-label small mb-0">' + f[1] + '</label><input class="form-control form-control-sm gate" data-k="' + f[0] + '" type="number" min="0" value="' + (g[f[0]] === undefined || g[f[0]] === null ? '' : g[f[0]]) + '" placeholder="no limit"' + dis + '></div>'; }).join('') + '</div><div class="small-muted mt-1">Empty = not checked. Per-rule limits: <input class="form-control form-control-sm d-inline-block w-auto" id="gRules" placeholder="TCA-JS-006=0, TCA-BPD-001=2" value="' + esc(Object.keys(g.rules || {}).map(function (k) { return k + '=' + g.rules[k]; }).join(', ')) + '"' + dis + '></div>';
  }
  function collectGates(el) { var g = { enabled: el.querySelector('#gEnabled').checked, rules: {} }; el.querySelectorAll('.gate').forEach(function (i) { if (i.value !== '') g[i.getAttribute('data-k')] = +i.value; }); el.querySelector('#gRules').value.split(',').forEach(function (p) { var m = p.trim().match(/^([A-Za-z0-9-]+)\s*=\s*(\d+)$/); if (m) g.rules[m[1].toUpperCase()] = +m[2]; }); return g; }
  function settingsPage(after) {
    T.setNav('settings'); app.innerHTML = '<h4>Settings' + helpLink('settings') + '</h4><div id="ws">Loading...</div><div id="st" class="mt-3"></div>';
    Promise.all([refreshInfo(), api('api/enterprise/workspace'), api('api/enterprise/policies')]).then(function (r) {
      var i = r[0], w = r[1], pols = r[2], f = i.features || {}, canManage = w.manage && !(i.demo && !i.user), dis = canManage ? '' : ' disabled';
      document.getElementById('ws').innerHTML = (i.demo && !i.user ? alertBox('info', '<i class="fa-solid fa-flask me-1"></i>Demo mode: the built-in rule settings apply to this temporary workspace. <a href="#/signup">Create an account</a> to choose policies, define quality gates and customise rules.') : '') +
        '<div class="row g-3"><div class="col-lg-6"><div class="card p-3 h-100"><h6>Workspace <span class="small-muted">' + esc(w.label) + ' (' + esc(w.kind) + ')</span></h6>' +
        '<label class="form-label small mb-0">Rule policy applied to every analysis of this workspace</label><select class="form-select form-select-sm mb-2" id="wPolicy"' + dis + '>' + pols.map(function (p) { return '<option value="' + esc(p.id) + '"' + (p.id === w.policy ? ' selected' : '') + '>' + esc(p.name) + (p.version ? ' v' + p.version : '') + (p.description ? ' - ' + esc(p.description) : '') + '</option>'; }).join('') + '</select>' +
        '<div class="small-muted mb-2">Central policies are maintained by administrators (Administration > Policies). "Workspace settings" uses the rules edited below.</div>' +
        '<div id="wGates"><h6 class="mt-2">Quality gate</h6><div class="small-muted mb-1">Used when the policy above is "Built-in defaults" or "Workspace settings"; a central policy carries its own gate.</div>' + gatesForm(w.gates, dis) + '</div>' +
        '<div class="mt-3"><button class="btn btn-primary btn-sm" id="wSave"' + dis + '>Save workspace</button><span id="wMsg" class="small ms-2"></span></div><div class="small-muted mt-2">Accepted findings in this workspace: ' + w.suppressions + ' · storage ' + fmtBytes(w.bytes || 0) + (w.quotaMb ? ' of ' + w.quotaMb + ' MB' : '') + '</div></div></div>' +
        '<div class="col-lg-6"><div class="card p-3 h-100"><h6>Notifications</h6>' + (f.notifications ? '<div class="small-muted mb-2">Sent when an analysis of this workspace completes or its quality gate fails.</div><label class="form-label small mb-0">Webhook URL (JSON POST)</label><input class="form-control form-control-sm mb-2" id="nHook" value="' + esc((w.notify || {}).webhook || '') + '"' + dis + '><label class="form-label small mb-0">E-mail recipients (comma separated)' + (f.smtp ? '' : ' - SMTP is not configured on this server') + '</label><input class="form-control form-control-sm mb-2" id="nMail" value="' + esc(((w.notify || {}).emails || []).join(', ')) + '"' + (f.smtp ? dis : ' disabled') + '><div class="form-check"><input class="form-check-input" type="checkbox" id="nDone"' + ((w.notify || {}).onComplete ? ' checked' : '') + dis + '><label class="form-check-label small" for="nDone">Every completed analysis</label></div><div class="form-check"><input class="form-check-input" type="checkbox" id="nFail"' + ((w.notify || {}).onGateFail ? ' checked' : '') + dis + '><label class="form-check-label small" for="nFail">Only when the quality gate fails</label></div>' : '<div class="small-muted">Notifications are not available for this workspace' + (i.user ? '' : ' (sign in)') + '.</div>') + '</div></div></div>';
      document.getElementById('wSave').addEventListener('click', function () { var body = { policy: document.getElementById('wPolicy').value, gates: collectGates(document.getElementById('wGates')) }; if (f.notifications) body.notify = { webhook: document.getElementById('nHook').value.trim(), emails: document.getElementById('nMail').value.split(',').map(function (s) { return s.trim(); }).filter(Boolean), onComplete: document.getElementById('nDone').checked, onGateFail: document.getElementById('nFail').checked }; post('api/enterprise/workspace', body, 'PUT').then(function () { state.id = null; state.report = null; settingsPage(function () { msg('wMsg', 'Saved. Existing reports were re-evaluated.'); }); }).catch(function (e) { msg('wMsg', String(e.message || e), 'text-danger'); }); });
      var custom = (document.getElementById('wPolicy').value || w.policy) === 'custom';
      T.loadSettings().then(function (d) { T.renderSettings(d, { readOnly: !custom || i.settingsReadOnly, readOnlyNote: custom ? undefined : 'A policy is selected for this workspace: its rules are shown below. Choose "Workspace settings" to edit rules here, or ask an administrator to change the policy.', note: custom ? 'Rule settings of this workspace, applied to every analysis while the policy "Workspace settings" is selected. Reports record the settings they were produced with.' : 'Rules of the selected policy (read-only).' }); if (typeof after === 'function') after(); });
    }).catch(function (e) { document.getElementById('ws').innerHTML = alertBox('danger', esc(e.message || e)); });
  }

  // ---------------- administration ----------------
  function adminPage(h) {
    T.setNav('admin'); if (!requireAdmin()) return; var sub = (h.split('/')[2] || 'policies'), i = info(), f = i.features || {};
    var tabs = [['policies', 'Policies'], ['teams', 'Teams']]; if (i.auth === 'builtin') tabs.push(['users', 'Users']); if (f.processCenter) tabs.push(['connections', 'Process Center connections']); if (f.audit) tabs.push(['audit', 'Audit trail']); tabs.push(['server', 'Server']);
    app.innerHTML = '<h4>Administration' + helpLink('administration') + '</h4><ul class="nav nav-tabs mb-3">' + tabs.map(function (t) { return '<li class="nav-item"><a class="nav-link' + (t[0] === sub ? ' active' : '') + '" href="#/admin/' + t[0] + '">' + t[1] + '</a></li>'; }).join('') + '</ul><div id="adm">Loading...</div>';
    ({ policies: adminPolicies, teams: adminTeams, users: adminUsers, connections: adminConnections, audit: adminAudit, server: adminServer }[sub] || adminPolicies)(h);
  }
  function adminPolicies(h) {
    var el = document.getElementById('adm'), pid = h.split('/')[3];
    if (pid) { editPolicy(el, pid === 'new' ? null : pid); return; }
    api('api/enterprise/policies').then(function (l) {
      el.innerHTML = '<div class="small-muted mb-2">Central rule policies: a named set of rule settings (enabled, severity, impact, weights, thresholds) with a quality gate. Workspaces select a policy in Settings; every report records the policy and version it was analysed with.</div><a class="btn btn-primary btn-sm mb-2" href="#/admin/policies/new"><i class="fa-solid fa-plus me-1"></i>New policy</a>' +
        '<table class="table table-sm table-hover bg-white"><thead><tr><th>Policy</th><th>Description</th><th>Version</th><th>Updated</th><th></th></tr></thead><tbody>' + l.filter(function (p) { return !p.builtin; }).map(function (p) { return '<tr><td><a href="#/admin/policies/' + esc(p.id) + '"><b>' + esc(p.name) + '</b></a> <span class="small-muted">' + esc(p.id) + '</span></td><td>' + esc(p.description) + '</td><td>' + p.version + '</td><td class="small-muted">' + esc(p.updatedAt) + ' ' + esc(p.updatedBy) + '</td><td class="text-end"><button class="btn btn-sm btn-outline-danger" data-pol="' + esc(p.id) + '"><i class="fa-solid fa-trash"></i></button></td></tr>'; }).join('') + '</tbody></table>' + (l.filter(function (p) { return !p.builtin; }).length ? '' : '<div class="small-muted">No policies yet. Workspaces use the built-in defaults or their own settings.</div>');
      el.querySelectorAll('[data-pol]').forEach(function (b) { b.addEventListener('click', function () { if (confirm('Delete policy ' + b.getAttribute('data-pol') + '? Workspaces using it fall back to the built-in defaults.')) del('api/enterprise/policies/' + b.getAttribute('data-pol')).then(function () { adminPolicies(h); }); }); });
    });
  }
  function editPolicy(el, pid) {
    (pid ? api('api/enterprise/policies/' + pid) : T.loadSettings().then(function (d) { return { id: '', name: '', description: '', gates: {}, document: d }; })).then(function (p) {
      el.innerHTML = '<a href="#/admin/policies" class="small">&larr; policies</a><div class="card p-3 mt-2 mb-3"><div class="row g-2"><div class="col-md-3"><label class="form-label small mb-0">Id</label><input class="form-control form-control-sm" id="pId" value="' + esc(p.id) + '"' + (pid ? ' disabled' : '') + ' placeholder="corporate-baseline"></div><div class="col-md-4"><label class="form-label small mb-0">Name</label><input class="form-control form-control-sm" id="pName" value="' + esc(p.name) + '"></div><div class="col-md-5"><label class="form-label small mb-0">Description</label><input class="form-control form-control-sm" id="pDesc" value="' + esc(p.description) + '"></div></div>' +
        '<h6 class="mt-3">Quality gate</h6><div id="pGates">' + gatesForm(p.gates, '') + '</div><div class="mt-3"><button class="btn btn-primary btn-sm" id="pSave"><i class="fa-solid fa-floppy-disk me-1"></i>Save policy</button><span id="pMsg" class="small ms-2"></span>' + (pid ? ' <span class="small-muted ms-2">version ' + p.version + ', updated ' + esc(p.updatedAt) + ' by ' + esc(p.updatedBy) + '</span>' : '') + '</div></div><h6>Rules of the policy</h6><div id="pst"></div>';
      var docState = p.document;
      function save(doc) { var body = { id: pid || document.getElementById('pId').value, name: document.getElementById('pName').value, description: document.getElementById('pDesc').value, gates: collectGates(document.getElementById('pGates')), settings: doc }; return (pid ? post('api/enterprise/policies/' + pid, body, 'PUT') : post('api/enterprise/policies', body)).then(function (r) { if (!pid) { nav('#/admin/policies/' + r.id); } return api('api/enterprise/policies/' + r.id).then(function (q) { docState = q.document; return { settings: q.document, warnings: [] }; }); }); }
      T.renderSettings(docState, { el: document.getElementById('pst'), readOnly: false, note: 'Enabled state, severity and impact per rule, severity weights and thresholds of this policy. Save from the button above or here.', save: save, reset: function () { return save({}); }, exportUrl: pid ? 'api/enterprise/policies/' + pid : 'api/settings?download=1', exportName: (pid || 'policy') + '.json' });
      document.getElementById('pSave').addEventListener('click', function () { document.getElementById('pst').querySelector('#stSave').click(); msg('pMsg', 'Saved.'); });
    }).catch(function (e) { el.innerHTML = alertBox('danger', esc(e.message || e)); });
  }
  function adminTeams() {
    var el = document.getElementById('adm');
    api('api/enterprise/teams').then(function (l) {
      el.innerHTML = '<div class="small-muted mb-2">A team is a shared workspace: members see the same analyses, policy and accepted findings. Team admins manage the team\'s policy and accepted findings. Members are user ids (e-mail addresses for built-in accounts); a directory group name matches users whose groups header contains it.</div>' +
        '<table class="table table-sm bg-white"><thead><tr><th>Team</th><th>Members</th><th>Admins</th><th>Group</th><th></th></tr></thead><tbody>' + l.map(function (t) { return '<tr><td><b>' + esc(t.name) + '</b> <span class="small-muted">' + esc(t.id) + '</span><div class="small-muted">' + esc(t.description) + '</div></td><td class="small">' + esc((t.members || []).join(', ')) + '</td><td class="small">' + esc((t.admins || []).join(', ')) + '</td><td class="small">' + esc(t.group) + '</td><td class="text-end text-nowrap"><button class="btn btn-sm btn-outline-secondary" data-edit="' + esc(t.id) + '"><i class="fa-solid fa-pen"></i></button> <button class="btn btn-sm btn-outline-danger" data-team="' + esc(t.id) + '"><i class="fa-solid fa-trash"></i></button></td></tr>'; }).join('') + '</tbody></table>' +
        '<div class="card p-3"><h6 id="tTitle">New team</h6><div class="row g-2"><div class="col-md-3"><input class="form-control form-control-sm" id="tId" placeholder="id (e.g. payments)"></div><div class="col-md-4"><input class="form-control form-control-sm" id="tNameF" placeholder="name"></div><div class="col-md-5"><input class="form-control form-control-sm" id="tDesc" placeholder="description"></div><div class="col-md-5"><input class="form-control form-control-sm" id="tMembers" placeholder="members: alice@example.com, bob@example.com"></div><div class="col-md-4"><input class="form-control form-control-sm" id="tAdmins" placeholder="team admins: alice@example.com"></div><div class="col-md-3"><input class="form-control form-control-sm" id="tGroup" placeholder="directory group (optional)"></div></div><div class="mt-2"><button class="btn btn-primary btn-sm" id="tSave">Save team</button> <button class="btn btn-outline-secondary btn-sm" id="tClear">Clear</button><span id="tMsg" class="small ms-2"></span></div></div>';
      var editing = null;
      el.querySelectorAll('[data-edit]').forEach(function (b) { b.addEventListener('click', function () { var t = l.filter(function (x) { return x.id === b.getAttribute('data-edit'); })[0]; editing = t.id; document.getElementById('tTitle').textContent = 'Edit team ' + t.name; document.getElementById('tId').value = t.id; document.getElementById('tId').disabled = true; document.getElementById('tNameF').value = t.name; document.getElementById('tDesc').value = t.description; document.getElementById('tMembers').value = (t.members || []).join(', '); document.getElementById('tAdmins').value = (t.admins || []).join(', '); document.getElementById('tGroup').value = t.group || ''; }); });
      el.querySelectorAll('[data-team]').forEach(function (b) { b.addEventListener('click', function () { var purge = confirm('Delete team ' + b.getAttribute('data-team') + '?\n\nOK = delete the team AND its workspace files permanently.\nCancel = keep everything.'); if (!purge) return; del('api/enterprise/teams/' + b.getAttribute('data-team') + '?purge=1').then(adminTeams); }); });
      document.getElementById('tClear').addEventListener('click', function () { editing = null; document.getElementById('tId').disabled = false; ['tId', 'tNameF', 'tDesc', 'tMembers', 'tAdmins', 'tGroup'].forEach(function (k) { document.getElementById(k).value = ''; }); document.getElementById('tTitle').textContent = 'New team'; });
      document.getElementById('tSave').addEventListener('click', function () { var body = { id: document.getElementById('tId').value, name: document.getElementById('tNameF').value, description: document.getElementById('tDesc').value, members: document.getElementById('tMembers').value, admins: document.getElementById('tAdmins').value, group: document.getElementById('tGroup').value }; (editing ? post('api/enterprise/teams/' + editing, body, 'PUT') : post('api/enterprise/teams', body)).then(function () { refreshInfo(); adminTeams(); }).catch(function (e) { msg('tMsg', String(e.message || e), 'text-danger'); }); });
    }).catch(function (e) { el.innerHTML = alertBox('danger', esc(e.message || e)); });
  }
  function adminUsers() {
    var el = document.getElementById('adm');
    api('api/auth/users').then(function (l) {
      el.innerHTML = '<div class="small-muted mb-2">Accounts created through sign-up. Administrators are designated in the admins properties file on the server (<code>admins=alice@example.com, bob@example.com</code>); the file is re-read when it changes.</div><table class="table table-sm bg-white"><thead><tr><th>Account</th><th>Name</th><th>Created</th><th>Last login</th><th>Storage</th><th>State</th><th></th></tr></thead><tbody>' +
        l.map(function (u) { return '<tr' + (u.disabled ? ' class="text-secondary"' : '') + '><td>' + esc(u.id) + (u.admin ? ' <span class="badge bg-warning text-dark">admin</span>' : '') + '</td><td>' + esc(u.name) + '</td><td class="small-muted">' + esc(u.createdAt) + '</td><td class="small-muted">' + esc(u.lastLogin || '-') + '</td><td>' + fmtBytes(u.workspaceBytes || 0) + '</td><td>' + (u.disabled ? 'disabled' : 'active') + '</td><td class="text-end text-nowrap"><button class="btn btn-sm btn-outline-secondary" data-toggle="' + esc(u.id) + '" data-dis="' + (u.disabled ? '0' : '1') + '">' + (u.disabled ? 'Enable' : 'Disable') + '</button> <button class="btn btn-sm btn-outline-secondary" data-pw="' + esc(u.id) + '">Reset password</button> <button class="btn btn-sm btn-outline-danger" data-user="' + esc(u.id) + '"><i class="fa-solid fa-trash"></i></button></td></tr>'; }).join('') + '</tbody></table>' + (l.length ? '' : '<div class="small-muted">No accounts yet.</div>');
      el.querySelectorAll('[data-toggle]').forEach(function (b) { b.addEventListener('click', function () { post('api/auth/users/' + encodeURIComponent(b.getAttribute('data-toggle')), { disabled: b.getAttribute('data-dis') === '1' }, 'PUT').then(adminUsers); }); });
      el.querySelectorAll('[data-pw]').forEach(function (b) { b.addEventListener('click', function () { var p = prompt('New password for ' + b.getAttribute('data-pw') + ' (8+ characters):'); if (p) post('api/auth/users/' + encodeURIComponent(b.getAttribute('data-pw')), { password: p }, 'PUT').then(function () { alert('Password set.'); }).catch(function (e) { alert(e.message || e); }); }); });
      el.querySelectorAll('[data-user]').forEach(function (b) { b.addEventListener('click', function () { if (confirm('Delete account ' + b.getAttribute('data-user') + ' and its workspace permanently?')) del('api/auth/users/' + encodeURIComponent(b.getAttribute('data-user'))).then(adminUsers); }); });
    }).catch(function (e) { el.innerHTML = alertBox('danger', esc(e.message || e)); });
  }
  function adminConnections() {
    var el = document.getElementById('adm');
    api('api/enterprise/connections').then(function (l) {
      el.innerHTML = '<div class="small-muted mb-2">Stored Process Center connections let users list process applications and import snapshots without entering credentials (the stored account needs read access to the repositories). The designer link template opens artifacts from the Remediation tab: placeholders {branchId}, {snapshotId}, {projectId}, {objectId}.</div>' +
        '<table class="table table-sm bg-white"><thead><tr><th>Connection</th><th>URL</th><th>User</th><th>Designer link</th><th></th></tr></thead><tbody>' + l.map(function (c) { return '<tr><td><b>' + esc(c.name) + '</b> <span class="small-muted">' + esc(c.id) + '</span>' + (c.type === 'studio' ? ' <span class="badge bg-info text-dark">Studio</span>' : '') + '</td><td class="small">' + esc(c.url) + (c.type === 'studio' ? ' <span class="small-muted">' + esc(c.contextRoot || '') + ' · ' + esc(c.auth || '') + '</span>' : '') + '</td><td class="small">' + esc(c.user) + (c.hasPassword || c.hasApiKey || c.hasToken ? '' : ' <span class="badge bg-warning text-dark">no secret</span>') + '</td><td class="small">' + esc(c.designerUrl) + '</td><td class="text-end text-nowrap"><button class="btn btn-sm btn-outline-secondary" data-edit="' + esc(c.id) + '"><i class="fa-solid fa-pen"></i></button> <button class="btn btn-sm btn-outline-danger" data-conn="' + esc(c.id) + '"><i class="fa-solid fa-trash"></i></button></td></tr>'; }).join('') + '</tbody></table>' +
        '<div class="card p-3"><h6 id="cTitle">New connection</h6><div class="row g-2"><div class="col-md-2"><input class="form-control form-control-sm" id="cId" placeholder="id"></div><div class="col-md-3"><input class="form-control form-control-sm" id="cName" placeholder="name"></div><div class="col-md-2"><select class="form-select form-select-sm" id="cType"><option value="pc">Process Center</option><option value="studio">Business Automation Studio</option></select></div><div class="col-md-5"><input class="form-control form-control-sm" id="cUrl" placeholder="https://processcenter.example.com:9443"></div><div class="col-md-2"><input class="form-control form-control-sm" id="cCtx" placeholder="context root (/bas)" value="/bas"></div><div class="col-md-3"><select class="form-select form-select-sm" id="cAuth"><option value="zen">Zen: user name + password</option><option value="zen-apikey">Zen: user name + API key</option><option value="bearer">Bearer token</option><option value="basic">Basic authentication</option></select></div><div class="col-md-2"><input class="form-control form-control-sm" id="cUser" placeholder="user"></div><div class="col-md-2"><input class="form-control form-control-sm" id="cPw" type="password" placeholder="password (empty keeps stored)"></div><div class="col-md-3"><input class="form-control form-control-sm" id="cKey" type="password" placeholder="API key (empty keeps stored)"></div><div class="col-md-3"><input class="form-control form-control-sm" id="cTok" type="password" placeholder="bearer token (empty keeps stored)"></div><div class="col-md-9"><input class="form-control form-control-sm" id="cDesigner" placeholder="designer link template, e.g. https://pc:9443/WebPD/jsp/bootstrap.jsp?containerRef={branchId}"></div></div><div class="small-muted mt-1">Studio: the URL is the platform (Zen) URL, the context root the Workflow Authoring route (default /bas); a Zen token is obtained from the platform with the user name and password or API key. Passwords, API keys and tokens are stored on the server for the connection.</div><div class="mt-2"><button class="btn btn-primary btn-sm" id="cSave">Save connection</button> <button class="btn btn-outline-secondary btn-sm" id="cClear">Clear</button><span id="cMsg" class="small ms-2"></span></div></div>';
      var editing = null;
      el.querySelectorAll('[data-edit]').forEach(function (b) { b.addEventListener('click', function () { var c = l.filter(function (x) { return x.id === b.getAttribute('data-edit'); })[0]; editing = c.id; document.getElementById('cTitle').textContent = 'Edit connection ' + c.name; document.getElementById('cId').value = c.id; document.getElementById('cId').disabled = true; document.getElementById('cName').value = c.name; document.getElementById('cType').value = c.type || 'pc'; document.getElementById('cCtx').value = c.contextRoot || '/bas'; document.getElementById('cAuth').value = c.auth && c.auth !== 'basic' ? c.auth : (c.type === 'studio' ? 'basic' : 'zen'); document.getElementById('cUrl').value = c.url; document.getElementById('cUser').value = c.user; document.getElementById('cPw').value = ''; document.getElementById('cKey').value = ''; document.getElementById('cTok').value = ''; document.getElementById('cDesigner').value = c.designerUrl || ''; }); });
      el.querySelectorAll('[data-conn]').forEach(function (b) { b.addEventListener('click', function () { if (confirm('Delete connection ' + b.getAttribute('data-conn') + '?')) del('api/enterprise/connections/' + b.getAttribute('data-conn')).then(adminConnections); }); });
      document.getElementById('cClear').addEventListener('click', function () { editing = null; document.getElementById('cId').disabled = false; ['cId', 'cName', 'cUrl', 'cUser', 'cPw', 'cKey', 'cTok', 'cDesigner'].forEach(function (k) { document.getElementById(k).value = ''; }); document.getElementById('cCtx').value = '/bas'; document.getElementById('cTitle').textContent = 'New connection'; });
      document.getElementById('cSave').addEventListener('click', function () { var body = { id: document.getElementById('cId').value, name: document.getElementById('cName').value, type: document.getElementById('cType').value, contextRoot: document.getElementById('cCtx').value, auth: document.getElementById('cAuth').value, url: document.getElementById('cUrl').value, user: document.getElementById('cUser').value, password: document.getElementById('cPw').value, apiKey: document.getElementById('cKey').value, token: document.getElementById('cTok').value, designerUrl: document.getElementById('cDesigner').value }; (editing ? post('api/enterprise/connections/' + editing, body, 'PUT') : post('api/enterprise/connections', body)).then(adminConnections).catch(function (e) { msg('cMsg', String(e.message || e), 'text-danger'); }); });
    }).catch(function (e) { el.innerHTML = alertBox('danger', esc(e.message || e)); });
  }
  function adminAudit() {
    var el = document.getElementById('adm');
    api('api/enterprise/audit?limit=500').then(function (l) { el.innerHTML = '<div class="small-muted mb-2">Newest first: analyses, deletions, settings and policy changes, accepted findings, sign-ups and logins, account and team administration. Stored in enterprise/audit.log (one JSON line per entry) and written to the server log.</div><table class="table table-sm bg-white"><thead><tr><th>Time</th><th>User</th><th>Workspace</th><th>Action</th><th>Details</th></tr></thead><tbody>' + l.map(function (e) { return '<tr><td class="small-muted text-nowrap">' + esc(e.time) + '</td><td>' + esc(e.user) + '</td><td class="small">' + esc(e.workspace) + '</td><td><b>' + esc(e.action) + '</b></td><td class="small mono">' + esc(JSON.stringify(e.details || {})) + '</td></tr>'; }).join('') + '</tbody></table>' + (l.length ? '' : '<div class="small-muted">No entries yet.</div>'); }).catch(function (e) { el.innerHTML = alertBox('danger', esc(e.message || e)); });
  }
  function adminServer() {
    var el = document.getElementById('adm'), i = info(), f = i.features || {};
    Promise.all([api('api/health'), fetch('api/metrics').then(function (r) { return r.text(); })]).then(function (r) {
      el.innerHTML = '<div class="row g-3"><div class="col-lg-5"><div class="card p-3"><h6>Health</h6><table class="table table-sm mb-0">' + Object.keys(r[0]).map(function (k) { return '<tr><td>' + esc(k) + '</td><td>' + esc(String(r[0][k])) + '</td></tr>'; }).join('') + '</table><div class="small-muted mt-2">Endpoints for monitoring: <code>api/health</code> (liveness JSON) and <code>api/metrics</code> (Prometheus text format).</div></div>' +
        '<div class="card p-3 mt-3"><h6>Deployment options in force</h6><table class="table table-sm mb-0">' + [['Demo mode', i.demo], ['Authentication', i.auth], ['Anonymous workspaces', i.anonymous], ['Sign-up', i.signup], ['Workers', f.workers], ['Quota per workspace (MB)', f.quotaMb || 'none'], ['Uploads kept after analysis', f.keepUploads], ['Retention of anonymous workspaces (days)', i.retentionDays || 'unlimited'], ['Process Center integration', f.processCenter], ['Notifications', f.notifications], ['SMTP configured', f.smtp], ['Designer link template', f.designerUrl]].map(function (x) { return '<tr><td>' + x[0] + '</td><td>' + esc(String(x[1])) + '</td></tr>'; }).join('') + '</table><div class="small-muted mt-2">Changed through the servlet context parameters, JVM properties or environment variables described in the <a href="#/help/deployment">deployment help</a>.</div></div></div>' +
        '<div class="col-lg-7"><div class="card p-3"><h6>Metrics</h6><pre class="code" style="max-height:600px">' + esc(r[1]) + '</pre></div></div></div>';
    }).catch(function (e) { el.innerHTML = alertBox('danger', esc(e.message || e)); });
  }

  // ---------------- Process Center ----------------
  function processCenterPage() {
    T.setNav('processcenter'); if (!requireUser()) return; var i = info(), f = i.features || {};
    app.innerHTML = '<h4>Process Center / Business Automation Studio' + helpLink('processcenter') + '</h4><div class="small-muted mb-3">Pick a snapshot on a Process Center or a Business Automation Studio (Cloud Pak for Business Automation): the server exports it and queues the analysis in your workspace, so nothing has to be exported and uploaded by hand. Toolkit exports are not listed (analyze them through the applications that use them).</div><div class="card p-3 mb-3"><div class="row g-2 align-items-end"><div class="col-md-3"><label class="form-label small mb-0">Saved definition</label><select class="form-select form-select-sm" id="pcConn"><option value="">Loading...</option></select></div><div class="col-md-2"><label class="form-label small mb-0">Repository</label><select class="form-select form-select-sm" id="pcType"><option value="pc">Process Center</option><option value="studio">Business Automation Studio</option></select></div><div class="col-md-5" id="pcUrlBox"><label class="form-label small mb-0">URL</label><input class="form-control form-control-sm" id="pcUrl" placeholder="https://processcenter.example.com:9443"></div><div class="col-md-2 studio-only"><label class="form-label small mb-0">Context root</label><input class="form-control form-control-sm" id="pcCtx" value="/bas"></div>' +
      '<div class="col-md-3 studio-only"><label class="form-label small mb-0">Authentication</label><select class="form-select form-select-sm" id="pcAuth"><option value="zen">Zen: user name + password</option><option value="zen-apikey">Zen: user name + API key</option><option value="bearer">Bearer token</option><option value="basic">Basic authentication</option></select></div><div class="col-md-2"><label class="form-label small mb-0">User</label><input class="form-control form-control-sm" id="pcUser"></div><div class="col-md-2" id="pcPwBox"><label class="form-label small mb-0">Password</label><input class="form-control form-control-sm" id="pcPw" type="password"></div><div class="col-md-2 studio-only" id="pcKeyBox"><label class="form-label small mb-0">API key</label><input class="form-control form-control-sm" id="pcKey" type="password"></div><div class="col-md-3 studio-only" id="pcTokBox"><label class="form-label small mb-0">Bearer token</label><input class="form-control form-control-sm" id="pcTok" type="password"></div><div class="col-md-1"><button class="btn btn-primary btn-sm w-100" id="pcGo">List</button></div></div><div class="small-muted mt-2" id="pcNote">Credentials entered here are used for this request only and are not stored.</div>' +
      '<div class="mt-2 d-flex flex-wrap gap-2 align-items-center"><input class="form-control form-control-sm w-auto" id="pcSaveName" placeholder="name, e.g. Production PC"><button class="btn btn-outline-primary btn-sm" id="pcSave"><i class="fa-solid fa-floppy-disk me-1"></i>Save this Process Center in my workspace</button><button class="btn btn-outline-danger btn-sm" id="pcDelete" hidden><i class="fa-solid fa-trash me-1"></i>Delete saved definition</button><span id="pcSaveMsg" class="small ms-2"></span></div><div class="small-muted mt-1">Saved definitions keep the URL, the user name and the password (stored on the server, readable by this workspace only) so the list can be opened with one click.</div></div><div id="pcApps"></div>';
    function repoFields() { var studio = document.getElementById('pcType').value === 'studio', auth = document.getElementById('pcAuth').value; document.querySelectorAll('.studio-only').forEach(function (e) { e.style.display = studio ? '' : 'none'; }); if (studio) { document.getElementById('pcKeyBox').style.display = auth === 'zen-apikey' ? '' : 'none'; document.getElementById('pcTokBox').style.display = auth === 'bearer' ? '' : 'none'; document.getElementById('pcPwBox').style.display = auth === 'zen' || auth === 'basic' ? '' : 'none'; document.getElementById('pcUser').parentNode.style.display = auth === 'bearer' ? 'none' : ''; } else { document.getElementById('pcPwBox').style.display = ''; document.getElementById('pcUser').parentNode.style.display = ''; } document.getElementById('pcUrl').placeholder = studio ? 'https://cpd.example.com (platform URL)' : 'https://processcenter.example.com:9443'; }
    document.getElementById('pcType').addEventListener('change', repoFields); document.getElementById('pcAuth').addEventListener('change', repoFields); repoFields();
    function repoBody() { var studio = document.getElementById('pcType').value === 'studio'; var b = { type: studio ? 'studio' : 'pc', url: document.getElementById('pcUrl').value.trim(), user: document.getElementById('pcUser').value, password: document.getElementById('pcPw').value }; if (studio) { b.contextRoot = document.getElementById('pcCtx').value; b.auth = document.getElementById('pcAuth').value; b.apiKey = document.getElementById('pcKey').value; b.token = document.getElementById('pcTok').value; } return b; }
    function loadConns(selectId) { api('api/enterprise/connections').then(function (l) { var sel = document.getElementById('pcConn'); var mine = l.filter(function (c) { return c.scope === 'workspace'; }), shared = l.filter(function (c) { return c.scope !== 'workspace'; });
      function opts(list) { return list.map(function (c) { return '<option value="' + esc(c.id) + '" data-url="' + esc(c.url) + '" data-user="' + esc(c.user) + '" data-scope="' + esc(c.scope) + '" data-type="' + esc(c.type || 'pc') + '" data-ctx="' + esc(c.contextRoot || '/bas') + '" data-auth="' + esc(c.auth || '') + '">' + esc(c.name) + (c.type === 'studio' ? ' (Studio)' : '') + '</option>'; }).join(''); }
      sel.innerHTML = (f.pcInlineCredentials ? '<option value="">Enter URL and credentials</option>' : '') + (mine.length ? '<optgroup label="Saved in this workspace">' + opts(mine) + '</optgroup>' : '') + (shared.length ? '<optgroup label="Shared by administrators">' + opts(shared) + '</optgroup>' : ''); if (selectId) sel.value = selectId;
      function upd() { var o = sel.options[sel.selectedIndex], stored = !!sel.value; if (stored) { document.getElementById('pcType').value = o.getAttribute('data-type') || 'pc'; document.getElementById('pcCtx').value = o.getAttribute('data-ctx') || '/bas'; if (o.getAttribute('data-auth')) document.getElementById('pcAuth').value = o.getAttribute('data-auth'); document.getElementById('pcUrl').value = o.getAttribute('data-url') || ''; document.getElementById('pcUser').value = o.getAttribute('data-user') || ''; document.getElementById('pcPw').value = ''; document.getElementById('pcKey').value = ''; document.getElementById('pcTok').value = ''; document.getElementById('pcSaveName').value = o.textContent.replace(' (Studio)', ''); repoFields(); } document.getElementById('pcDelete').hidden = !(stored && o.getAttribute('data-scope') === 'workspace'); document.getElementById('pcNote').textContent = stored ? 'URL and user name come from the saved definition; the stored password is used unless you enter one. Change the URL or the user to override them for this request.' : 'The Process Center URL and the credentials entered here are used for this request only unless you save them below.'; }
      sel.addEventListener('change', upd); upd(); }).catch(function () {}); }
    loadConns();
    document.getElementById('pcSave').addEventListener('click', function () { var name = document.getElementById('pcSaveName').value.trim() || document.getElementById('pcUrl').value.replace(/^https?:\/\//, ''); var sel = document.getElementById('pcConn'), o = sel.options[sel.selectedIndex]; var existing = sel.value && o.getAttribute('data-scope') === 'workspace' ? sel.value : ''; var body = repoBody(); body.name = name;
      (existing ? post('api/enterprise/workspace/connections/' + existing, body, 'PUT') : post('api/enterprise/workspace/connections', body)).then(function (c) { msg('pcSaveMsg', 'Saved as "' + c.name + '".'); loadConns(c.id); }).catch(function (e) { msg('pcSaveMsg', String(e.message || e), 'text-danger'); }); });
    document.getElementById('pcDelete').addEventListener('click', function () { var sel = document.getElementById('pcConn'); if (!sel.value || !confirm('Delete the saved definition "' + sel.options[sel.selectedIndex].textContent + '"?')) return; del('api/enterprise/workspace/connections/' + sel.value).then(function () { msg('pcSaveMsg', 'Deleted.'); document.getElementById('pcUrl').value = ''; document.getElementById('pcUser').value = ''; loadConns(); }).catch(function (e) { msg('pcSaveMsg', String(e.message || e), 'text-danger'); }); });
    document.getElementById('pcGo').addEventListener('click', function () {
      var conn = document.getElementById('pcConn').value, user = document.getElementById('pcUser').value, pw = document.getElementById('pcPw').value, el = document.getElementById('pcApps'); el.innerHTML = '<span class="spinner-border spinner-border-sm"></span> Connecting ...';
      var rb = repoBody(), url = rb.url;
      (conn ? api('api/enterprise/connections/' + conn + '/apps?url=' + encodeURIComponent(url) + '&user=' + encodeURIComponent(user) + '&password=' + encodeURIComponent(pw) + '&token=' + encodeURIComponent(rb.token || '') + '&apiKey=' + encodeURIComponent(rb.apiKey || '')) : post('api/enterprise/pc/apps', rb)).then(function (apps) {
        el.innerHTML = '<div class="card p-3"><h6>' + apps.length + ' process application(s)</h6><div class="small-muted mb-2">Snapshots are grouped by track; <span class="badge bg-light text-dark border">tip</span> is the current working version of the track, <span class="badge bg-success">active</span> the active snapshot.</div><table class="table table-sm table-hover mb-0"><thead><tr><th>Application</th><th>Track</th><th>Snapshot</th><th>Created</th><th></th></tr></thead><tbody>' + apps.map(function (a) { var rows = []; (a.tracks || []).forEach(function (t) { (t.snapshots || []).forEach(function (s, k) { rows.push({ t: t, s: s, first: k === 0 }); }); }); return rows.map(function (r, k) { var s = r.s, t = r.t; return '<tr>' + (k === 0 ? '<td rowspan="' + rows.length + '"><b>' + esc(a.name) + '</b> <span class="small-muted">' + esc(a.acronym) + '</span></td>' : '') + (r.first ? '<td rowspan="' + t.snapshots.length + '">' + esc(t.name) + (t.isDefault ? ' <span class="badge bg-light text-dark border">default</span>' : '') + '</td>' : '') + '<td>' + esc(s.name) + (s.tip ? ' <span class="badge bg-light text-dark border">tip</span>' : '') + (s.active ? ' <span class="badge bg-success">active</span>' : '') + '</td><td class="small-muted">' + esc(s.createdOn || '') + '</td><td class="text-end"><button class="btn btn-sm btn-outline-primary" data-snap="' + esc(s.id) + '" data-app="' + esc(a.acronym || a.name) + '" data-name="' + esc(s.name) + '"><i class="fa-solid fa-download me-1"></i>Import &amp; analyze</button></td></tr>'; }).join('') || '<tr><td><b>' + esc(a.name) + '</b></td><td colspan="4" class="small-muted">no snapshots</td></tr>'; }).join('') + '</tbody></table></div><div id="pcJobs" class="mt-3"></div>';
        el.querySelectorAll('[data-snap]').forEach(function (b) { b.addEventListener('click', function () { b.disabled = true; var body = repoBody(); body.snapshotId = b.getAttribute('data-snap'); body.app = b.getAttribute('data-app'); body.snapshot = b.getAttribute('data-name'); body.toolkits = false; if (conn) { body.connection = conn; if (!user) { delete body.user; delete body.password; } }
          document.getElementById('pcJobs').innerHTML = alertBox('info', '<span class="spinner-border spinner-border-sm me-2"></span>Exporting ' + esc(body.app) + ' ' + esc(body.snapshot) + ' from the Process Center ...');
          post('api/enterprise/pc/import', body).then(function (job) { function poll() { api('api/jobs/' + job.id).then(function (j) { if (j.status === 'done') { document.getElementById('pcJobs').innerHTML = alertBox('success', 'Analysis done: <a href="#/report/' + esc(j.reportId) + '">open the report</a>.'); b.disabled = false; return; } if (j.status === 'failed') { document.getElementById('pcJobs').innerHTML = alertBox('danger', 'Failed: ' + esc(j.error)); b.disabled = false; return; } document.getElementById('pcJobs').innerHTML = alertBox('info', '<span class="spinner-border spinner-border-sm me-2"></span>' + (j.status === 'queued' ? 'Queued (position ' + j.position + ')' : 'Analyzing: ' + esc(j.progress)) + ' ...'); setTimeout(poll, 1000); }); } poll(); }).catch(function (e) { document.getElementById('pcJobs').innerHTML = alertBox('danger', esc(e.message || e)); b.disabled = false; }); }); });
      }).catch(function (e) { el.innerHTML = alertBox('danger', esc(e.message || e)); });
    });
  }

  // ---------------- help ----------------
  function helpPage(h) { T.setNav('help'); var anchor = h.split('/')[2] || ''; app.innerHTML = '<iframe src="help/index.html' + (anchor ? '#' + esc(anchor) : '') + '" style="width:100%;height:calc(100vh - 90px);border:0;background:#fff" title="Help"></iframe>'; }

  // ---------------- registration ----------------
  T.routes['#/'] = dashboard; T.routes['#/analyze'] = analyzePage; T.routes['#/jobs'] = jobsPage; T.routes['#/login'] = loginPage; T.routes['#/signup'] = signupPage; T.routes['#/account'] = accountPage;
  T.routes['#/settings'] = settingsPage; T.routes['#/admin'] = adminPage; T.routes['#/processcenter'] = processCenterPage; T.routes['#/help'] = helpPage;
  buildNav();
})();
