package tca.engine;

import java.util.*;
import tca.rules.Finding;

/** Printable PDF reports rendered by the engine (findings report, toolkit usage report) - used by the web app and the BAW process application. */
public final class PdfReport {
    private PdfReport() {}
    static final String NOTE = "Static analysis is advisory: confirm each finding in the application context before changing production logic. Generated by TWX Code Analyzer.";

    static String intro(Report r) { return r.appName + " (" + r.acronym + ") " + r.snapshotName + "  |  " + r.fileName + (r.bawVersion.isEmpty() ? "" : "  |  " + r.bawVersion + " export") + "  |  analyzed " + r.analyzedAt + "  |  engine " + r.engineVersion; }

    /** Findings report: summary, rules present in the selection, ranked findings (already filtered / sorted by the caller). */
    public static byte[] findings(Report r, List<Finding> rows, String filterDescription) {
        Pdf p = new Pdf(true); p.footer = "TWX Code Analyzer - " + r.appName + " " + r.snapshotName;
        p.heading("TWX Code Analyzer report", 16); p.paragraph(intro(r), 9, 0.35);
        Map<String, Object> summary = summary(r);
        p.heading("Summary", 12);
        List<String[]> srow = new ArrayList<>(); @SuppressWarnings("unchecked") Map<String, Integer> bs = (Map<String, Integer>) summary.get("bySeverity");
        srow.add(new String[] { summary.get("healthScore") + " / 100", String.valueOf(summary.get("findings")), String.valueOf(bs.get("CRITICAL")), String.valueOf(bs.get("MAJOR")), String.valueOf(bs.get("MINOR")), String.valueOf(bs.get("INFO")), String.valueOf(r.objectCount), String.valueOf(r.toolkitCount), r.scriptCount + " (" + r.scriptLines + " lines)" });
        p.table(new String[] { "Health", "Findings (all)", "Critical", "Major", "Minor", "Info", "Objects", "Toolkits", "Scripts" }, new double[] { .1, .12, .09, .09, .09, .09, .1, .1, .22 }, srow, 9);
        for (Map<String, Object> d : r.diagnostics) p.paragraph(String.valueOf(d.get("message")), 8, 0.35);
        if (filterDescription != null && !filterDescription.isEmpty()) p.paragraph("Selection: " + filterDescription, 8, 0.35);
        Map<String, Integer> byRule = new LinkedHashMap<>(); for (Finding f : rows) byRule.merge(f.ruleId, 1, Integer::sum);
        p.heading("Rules in this report (" + byRule.size() + ")", 12);
        List<Map<String, Object>> rules = new ArrayList<>(); for (Map<String, Object> rj : r.rules) if (byRule.containsKey(String.valueOf(rj.get("id")))) rules.add(rj);
        Collections.sort(rules, new Comparator<Map<String, Object>>() { public int compare(Map<String, Object> a, Map<String, Object> b) { return byRule.get(String.valueOf(b.get("id"))) - byRule.get(String.valueOf(a.get("id"))); } });
        List<String[]> rr = new ArrayList<>(); for (Map<String, Object> rj : rules) rr.add(new String[] { "**" + rj.get("id") + " " + rj.get("title") + ("medium".equals(rj.get("confidence")) ? " (needs review)" : ""), String.valueOf(rj.get("severity")), String.valueOf(rj.get("category")), String.valueOf(byRule.get(String.valueOf(rj.get("id")))), String.valueOf(rj.get("remediation")) });
        p.table(new String[] { "Rule", "Severity", "Category", "Findings", "Remediation" }, new double[] { .30, .08, .10, .07, .45 }, rr, 8);
        p.heading("Findings (" + rows.size() + ", ranked)", 12);
        List<String[]> fr = new ArrayList<>(); int i = 0;
        for (Finding f : rows) fr.add(new String[] { String.valueOf(++i), f.severity + " " + f.score, "**" + f.ruleId + "\n" + f.title, f.path(), f.message + (f.evidence.isEmpty() ? "" : "\n" + f.evidence) });
        p.table(new String[] { "#", "Severity", "Rule", "Artifact path", "Finding" }, new double[] { .04, .08, .16, .30, .42 }, fr, 7.5);
        p.paragraph(NOTE, 8, 0.35);
        return p.build();
    }

    /** Toolkit usage report for the selected logical toolkits (entries of report.toolkitUsage.toolkits). */
    @SuppressWarnings("unchecked")
    public static byte[] toolkitUsage(Report r, List<Map<String, Object>> toolkits) {
        Pdf p = new Pdf(true); p.footer = "TWX Code Analyzer - toolkit usage - " + r.appName + " " + r.snapshotName;
        p.heading("Toolkit usage", 16); p.paragraph(intro(r), 9, 0.35);
        p.paragraph("Used: an application artifact references the toolkit artifact by id (call, binding, type, include). Possible usage: an application script instantiates a business object with new tw.object.Name() that only this toolkit declares. No detected usage is not proof that the toolkit can be removed: lookups by name at runtime and references from other toolkits still need a review.", 8, 0.35);
        p.heading("Toolkits (" + toolkits.size() + ")", 12);
        List<String[]> rows = new ArrayList<>();
        for (Map<String, Object> t : toolkits) rows.add(new String[] { "**" + t.get("name") + " " + t.get("acronym") + (Boolean.TRUE.equals(t.get("system")) ? " (system)" : ""), snapshots(t), label(String.valueOf(t.get("status"))), String.valueOf(t.get("objects")), String.valueOf(t.get("used")), String.valueOf(t.get("possible")), join((List<Object>) t.get("usedByToolkits")) });
        p.table(new String[] { "Toolkit", "Snapshots", "Status", "Artifacts", "Used", "Possible", "Referenced by other toolkits" }, new double[] { .24, .18, .12, .08, .07, .08, .23 }, rows, 8);
        for (Map<String, Object> t : toolkits) {
            List<Map<String, Object>> objs = (List<Map<String, Object>>) t.get("objectList"); boolean multi = ((List<Object>) t.get("snapshots")).size() > 1;
            p.heading(t.get("name") + " - " + label(String.valueOf(t.get("status"))), 11);
            if (objs.isEmpty()) { p.paragraph("No application artifact references this toolkit.", 8, 0.35); continue; }
            Map<String, List<Map<String, Object>>> byType = new TreeMap<>(); for (Map<String, Object> o : objs) { String k = String.valueOf(o.get("typeLabel")); List<Map<String, Object>> l = byType.get(k); if (l == null) { l = new ArrayList<>(); byType.put(k, l); } l.add(o); }
            for (Map.Entry<String, List<Map<String, Object>>> e : byType.entrySet()) {
                List<Map<String, Object>> l = e.getValue(); Collections.sort(l, new Comparator<Map<String, Object>>() { public int compare(Map<String, Object> a, Map<String, Object> b) { return String.valueOf(a.get("name")).compareTo(String.valueOf(b.get("name"))); } });
                List<String[]> or = new ArrayList<>();
                for (Map<String, Object> o : l) { StringBuilder ub = new StringBuilder(); for (Map<String, Object> u : (List<Map<String, Object>>) o.get("usedBy")) ub.append(ub.length() > 0 ? "\n" : "").append(u.get("typeLabel")).append(' ').append(u.get("name")); or.add(new String[] { o.get("name") + (multi ? "  (" + o.get("snapshot") + ")" : ""), label(String.valueOf(o.get("status"))), ub.toString(), String.valueOf(o.get("evidence")) }); }
                p.paragraph(e.getKey() + " (" + l.size() + ")", 9, 0);
                p.table(new String[] { "Toolkit artifact", "Status", "Used by (application)", "Evidence" }, new double[] { .28, .12, .38, .22 }, or, 7.5);
            }
        }
        p.paragraph("Generated by TWX Code Analyzer.", 8, 0.35);
        return p.build();
    }
    /** Same filter as the findings tab: sev=CRITICAL,MAJOR cat= rule= type= conf= q= sort=score|object|rule. */
    public static List<Finding> filterFindings(Report r, Map<String, String> q) {
        Set<String> sev = new HashSet<>(); if (q.containsKey("sev") && !q.get("sev").isEmpty()) sev.addAll(Arrays.asList(q.get("sev").split(",")));
        String cat = q.get("cat"), rule = q.get("rule"), type = q.get("type"), conf = q.get("conf"), text = q.containsKey("q") ? q.get("q").toLowerCase() : "";
        List<Finding> l = new ArrayList<>();
        for (Finding f : r.findings) { if (!sev.isEmpty() && !sev.contains(f.severity)) continue; if (cat != null && !cat.isEmpty() && !f.category.equals(cat)) continue; if (rule != null && !rule.isEmpty() && !f.ruleId.equals(rule)) continue; if (type != null && !type.isEmpty() && !f.objectTypeLabel.equals(type)) continue; if (conf != null && !conf.isEmpty() && !f.confidence.equals(conf)) continue; if (!text.isEmpty() && !(f.path() + " " + f.message + " " + f.title).toLowerCase().contains(text)) continue; l.add(f); }
        String sort = q.get("sort");
        if ("object".equals(sort)) Collections.sort(l, new Comparator<Finding>() { public int compare(Finding a, Finding b) { int c = (a.objectName + a.itemName).compareTo(b.objectName + b.itemName); return c != 0 ? c : b.score - a.score; } });
        else if ("rule".equals(sort)) Collections.sort(l, new Comparator<Finding>() { public int compare(Finding a, Finding b) { int c = a.ruleId.compareTo(b.ruleId); return c != 0 ? c : b.score - a.score; } });
        return l;
    }
    public static String describe(Map<String, String> q) { StringBuilder b = new StringBuilder(); String[][] k = { { "sev", "severity" }, { "cat", "category" }, { "rule", "rule" }, { "type", "artifact type" }, { "conf", "confidence" }, { "q", "text" } }; for (String[] e : k) if (q.containsKey(e[0]) && !q.get(e[0]).isEmpty()) b.append(b.length() > 0 ? ", " : "").append(e[1]).append(" = ").append(q.get(e[0])); return b.toString(); }
    static String label(String s) { return s.equals("used") ? "Used" : s.equals("possible") ? "Possible usage" : "No detected usage"; }
    @SuppressWarnings("unchecked") static String snapshots(Map<String, Object> t) { StringBuilder b = new StringBuilder(); for (Map<String, Object> s : (List<Map<String, Object>>) t.get("snapshots")) b.append(b.length() > 0 ? "\n" : "").append(s.get("snapshot")); return b.toString(); }
    static String join(List<Object> l) { StringBuilder b = new StringBuilder(); if (l != null) for (Object o : l) b.append(b.length() > 0 ? ", " : "").append(o); return b.toString(); }
    @SuppressWarnings("unchecked") static Map<String, Object> summary(Report r) { return (Map<String, Object>) r.toJson().get("summary"); }
}
